### ISSUE TITLE
Design buffer mechanism

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#139]
A buffer mechanism is to be designed so that the client can buffer a number of steps before starting the reproduction. Things to be looked at/evaluated:
- [ ] How is this being done in say Youtube/Vimeo/etc?
- [ ] Best way to cache the timesteps. Any JS library available?
- [ ] How to determine when a buffer is big enough?
- [ ] How to manage interactions with the simulations if the simulation has been buffered (entirely disabled as when replaying a recording?)
- [ ] Do we need something adaptive?

**Comment by gidili** [comment]
Obsolete.
