### ISSUE TITLE
Add array API

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto#16]
It would be great to use Geppetto for basic data analysis / descriptive statistics, without having to embed trivialities (such as calculating an average) in the model description itself. In other words, at the moment it is possible to simulate a model and produce timeseries ([ti, xi] pairs) to be plotted, but what if we would like to calculate/plot  functions of x (examples: calculate mean(x) or plot a histogram of cos(x)). Having an (numpy/matlab/R/scilab/...) arraylike data structure, with builtin support for arraywise base mathematical functions and indexing would be fantastic -- and eliminate the need of firing scipy/matlab/etc just to perform trivial exploratory tasks. 

Random wishlist -- given an array _x_ with simulation results

```
    plot(abs(x[-1000:end])) //intuitive indexing, get the last 1000 points
    histogram((x-mean(x))/10)//basic statistics and operations involving arrays/scalars
```

**Comment by LordKrabo** [comment]
Hi @borismarin Can I add this to sprint 82?

**Comment by borismarin** [comment]
If you can find someone who will do it, absolutely!

**Comment by borismarin** [comment]
That is a "macro" card,  we will need design and prototyping sessions - I'd
be happy to participate, but I don't have the bandwidth to lead it at the
moment.

**Comment by LordKrabo** [comment]
Would PypeR be worth using? http://www.webarray.org/softwares/PypeR/

**Comment by borismarin** [comment]
I guess numpy / scipy would be a natural choice (no need to fire up R etc)

**Comment by tarelli** [comment]
@LordKrabo @borismarin I cleared the assignee for this and every other card in the idea column, the idea that in that column it meant "who proposed the idea" rather than "who will fix it" is clearly non standard and confusing. If someone wants to know who proposed the idea they'll just have to click on the card. @LordKrabo thanks for helping keeping the board clean, keep it up :)

**Comment by borismarin** [comment]
@LordKrabo maybe [that](https://github.com/nicolaspanel/numjs) ?

**Comment by LordKrabo** [comment]
The image manipulation stuff seems interesting. Is there any code that I could test it on?

**Comment by borismarin** [comment]
They seem to have a decent array-like abstraction, which supports fundamental operations. I was originally thinking of timeseries analysis, but VFB (@tarelli) people might also be interested in the image analysis functionality.
