### ISSUE TITLE
Add API commands to move the camera using absolute coordinates

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#160]
At the moment we have the controls hooked up with API commands to perform relative camera movements, see this [link](https://github.com/openworm/org.geppetto.frontend/blob/4442a2642e1e855d761974116f9abf7eb6b0dbfe/src/main/webapp/js/components/dev/cameracontrols/CameraControls.js#L16).
This card is about adding the ability to set the camera in a specific position/rotation using absolute coordinates.
See these links for an example of the current functionality:
https://github.com/openworm/org.geppetto.frontend/blob/2b2cce23dd9564e8646ac8ffdda55256319aaa98/src/main/webapp/js/geppetto-objects/G.js#L401
https://github.com/openworm/org.geppetto.frontend/blob/ef2402d0b2ce36b012aefb0d0dd0d0b4a57a8737/src/main/webapp/js/GEPPETTO.js#L439
- [x] Add API command to G object setCameraPosition/Rotation
- [x] Send command to the console when mouse is release after having moved the camera
- [x] Add documentation for setting the camera position

**Comment by slarson** [comment]
Just wanted to ping this issue to see if it could get into the next sprint perhaps to help address openworm/org.geppetto.samples#25 as it seems to be backlogged

**Comment by tarelli** [comment]
If there's anyone with time to add this in the next sprint or even in the current one I'd be more than happy to assist.

**Comment by tarelli** [comment]
@samredway assigned to you!

**Comment by samredway** [comment]
Thanks @tarelli  I will spend some time with it over the weekend and hopefully get it done.

**Comment by samredway** [comment]
So I am looking at this and it is getting tricky. I am hoping for some advice or guidance. 

It is easy to set the camera to an absolute position using the existing functions e.g.

                /**
		 * Sets camera position by absolute values
		 * @param {Integer} x, x location of camera to pan to (absolute)
		 * @param {Integer} y, y location of camera to pan to (absolute)
		 * @param {Integer} z, zoom
                 * @param{Integer} xr, rotation around x (absolute)
                 * @param{Integer} yr. rotation around y (absolute)
                 * @param{Integer} zr,  rotation around z (absolute)
		 */
         
		setCameraPosition: function(x, y, z) {
                    this.resetCamera();
                    this.incrementCameraPan(x, y);
                    this.incrementCameraZoom(z);
                    this.incrementCameraRotate(xr, yr, yz);
		},

This function now can be placed in GEPPETTO.js and called from G.js ... 

This will do the job. It is a bit confusing having to pass in so many variables in one go and it may be nicer to break it into two functions i.e. setCameraPosition and setCameraRotation. That however would be much more tricky as I would not simply be able to call resetCamera to establish the starting position as that would clear both the rotation and the pan meaning you could not set both, it would be either or or I would have to figure out how the resetCamera function works and break it down to use in each of the respective setCamera functions.

Is what I have what is wanted or do I need to break it down a bit?

For part two of the issue, what is it that needs to be sent to the console exactly? Do you mean that when you have finished rotating then the absolute postion of the camera is sent to console? 

Thanks.

**Comment by tarelli** [comment]
@samredway thanks for looking into this Sam, what you are proposing might indeed work! I think one method will do for now, and it plays well with pt2. For part two of the issue yes that's the idea, sending to the console the command with the appropriate parameters that would make the camera go exactly in the position where the user is placing it so that it could be reproduced programmatically.

**Comment by samredway** [comment]
@tarelli That sounds kind of tricky. To do it we need to essentially have a static counter that holds the absolute values of x,y,z,xr,yr,zr - we can then send those to the console on release, or have a G.getCameraPosition() function which kind of makes more sense to me? Or we can even have a display on screen showing camera co-ordinates. 
That way if someone wants to go back to a set position they can getCameraPostion() for the absolute co-ordinates and then go back with setCameraPosition on the next occasion...
As I say I think to do this I need to define a static class atrbute which would be an object holding the absolute co-ordinates and just increment/decrementing when the functions incrementCameraRotation etc are called.
Does that sound like the answer you are after?

**Comment by samredway** [comment]
@tarelli I am thinking along these lines: 

The easiest way to do what needs to be done would be to have a static object holding a record of the cameras absolute co-ordinates e.g.

var cameraAbsolutePosition = {
    x: 0;
    y: 0;
    z: 0;
    rx: 0;
    ry: 0;
    rz: 0;
}

obviously when resetCamera is called it looks like above. Then on each increment and decrement call the relevant obect property is updated. This means that we can get the absolute position at any time with a function like getCameraPosition().

So a user can call the getter when the camera has been manually set to his liking and return to that position at any time with the setCameraPostion function described above. 

I may be wrong (there may already be a property holding the absolute postion) but I think this means defining a new GEPPETTO property and adding to each camera movement function a line updating the cameraAbsolutePosition  object.

Does this sound like a reasonable approach?

**Comment by tarelli** [comment]
@samredway 
I don't think we need to save the increments, every Object3D in three.js has a `matrixWorld` object that can be used to read the position. The position can then be set using `.setFromMatrixPosition` method, something like `pos.setFromMatrixPosition(camera.matrixWorld);` have a look at the documentation here: 
[Camera](http://threejs.org/docs/#Reference/Cameras/Camera)
[Object3D](http://threejs.org/docs/#Reference/Core/Object3D) 
cc @borismarin

**Comment by samredway** [comment]
Hi Matteo,
I'm sorry to say that I have been unable to make headway on this issue.
The key problem is firstly hat I just do not have the level currently to understand all the maths etc going on in the problem and secondly I am now very limited for time as quite unexpectedly I have been hired for a new job that is taking up all my time right now, so I won't be able to contribute at the moment as planned.
I feel disappointed that I haven't been able to make a substantial contribution at this stage but still think it is a great project and will be keeping my eye on it. 
Next term I am conveniently doing an undergraduate maths module covering vector maths through to linear equations etc. so that will bring me up to the necessary level to understand what is going on with three js . It's quite likely that I will come back and revisit the project at this time with a clearer view.
In the meantime best wishes.
Sam

Date: Sat, 30 May 2015 08:00:17 -0700

**Comment by felipetavares** [comment]
@tarelli by:

> Send command to the console when mouse is release after having moved the camera

you mean send something like "G.setCameraRotation(...)" from TrackballControls or from the widget controls?

**Comment by gidili** [comment]
@felipetavares after releasing the mouse (which is using the trackball controls) it should show the equivalent command in the console to achieve whatever rotation / panning was performed, but it should not execute it (since the trackball controls are taking care of that).

When clicking from the camera controls components (the control bar on the left) it is currently executing the command in the console (setCameraRotation, etc.).

@tarelli makes sense?

**Comment by felipetavares** [comment]
I think I'm almost finished on this.
For the documentation, is something like this sufficient?

```
			/**
			 * Sets camera position
			 *
			 * @command - G.setCameraPosition()
			 * @param {Integer} x - new x axis position for the camera
			 * @param {Integer} y - new y axis position for the camera
			 * @param {Integer} z - new z axis position for the camera
			 */
			setCameraPosition: function(x, y, z) {
				GEPPETTO.setCameraPosition(x, y, z);

				return GEPPETTO.Resources.CAMERA_SET_POSITION;
			},
```

**Comment by gidili** [comment]
@felipetavares yeah that looks good!

**Comment by tarelli** [comment]
@felipetavares reopening this, waiting for the PR to review it and merge it!
