### ISSUE TITLE
Add support to display equations

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#173]
Mathjax is a good candidate library for this http://www.mathjax.org/about/

**Comment by borismarin** [comment]
FYI, the new [lems expression parser](https://github.com/borismarin/lems-expr-parser/) can now [render LaTeX](https://github.com/borismarin/lems-expr-parser/blob/master/src/test/java/parser/test/AdaptExpressionToLangTest.java#L35) from LEMS expressions. Mathjax supports the LaTeX notation, so as long as Geppetto adopts LEMS syntax for expressions (or we can adapt the parser to handle yours - no one likes .geq.) we're good to go.

**Comment by LordKrabo** [comment]
@borismarin @tarelli Add to sprint 75?
