### ISSUE TITLE
Extend events framework

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#227]
- [x] Add ability to declare event types
- [x] Add selection event
- [x] Add ability for widgets to register actions in response to event triggering
- [x] Add ability for Geppetto to be a command provider
- [x] Add ability to TreeVisualizerController to react to SELECT event. When a SELECT event is triggered if the Visualizer is properly configured* the TreeVisualizerController will create (if it doesn't exist already) a "static" instance of the TreeVisualizer and will set is content to the selected note.

(*) The tree visualizer controller (is it a generic config that could be reused for any widget?) can be configured to have a static instance of the tree visualizer created when things are selected in Geppetto. This instance of the widget is reused every time something is selected. If other instances of the widget exist (for instance user created) these will be ignored. If the "static" instance is destroyed and then the user clicks on an entity the "static" instance is recreated.

At the moment

*Widget declares an event A for a given Node type*
getCommands: function(node) {
				groups = [
				          [{label:"Open with D3 Widget",
				        	action: GEPPETTO.TreeVisualiserControllerD3.actionMenu,
				        	icon:"icon3",
				        	option: {option1: "option1"}}]
				          ];
				return groups;
			},

Note that the caller of the action will pass the data and the options, where the data is the nodes that are in the context for the action (e.g. what nodes are selected, what nodes need to be plotted, etc.)

*Widget contributes an action to trigger event A to the context menu*

I can contribute commands for this type of node, whenever such a node exists and you want to know what commands are available ask me.

registerNewCommandProvider(["AspectSubTreeNode"], GEPPETTO.TreeVisualiserControllerDAT.getCommands);

To be added as part of this card:

I can react to an event
 
registerNewAction(["Node"],EVENT_TYPE, GEPPETTO.TreeVisualiserControllerDAT.actionMenu);

*Widget reacts to event A for a given Node type*

 GEPPETTO.TreeVisualiserControllerD3.actionMenu, is called

**Comment by tarelli** [comment]
@jrmartin is this in review?

**Comment by jrmartin** [comment]
@tarelli Working on it today, started Friday, forgot to move it to this column though

**Comment by jrmartin** [comment]
Events are going to be working the following way after refactoring: 

To trigger an event, do:
GEPPETTO.trigger("simulation:restart")

Method [GEPPETTO.events()](https://github.com/openworm/org.geppetto.frontend/blob/6f0790292dd7b4eac00b3380f6628f246b22a916/src/main/webapp/js/GEPPETTO.js#L81) which is only called in initialization, has code that knows what to do once that event is fired. For our example above, it calls the widgetlistener with an update event to delete all widgets.
