### ISSUE TITLE
Extend/Improve TreeVisualiser

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto#246]
- [x] Check getChildren() is working fine for every node
- [x] Return the same type of object in any getChildren() method. (getChildren() for EntityNode returns a js array while the other getChildren() returns a backbone collection)
- [x] Populate ModelTree when getChildren() for Model Tree node is executed.
- [x] Add a css class to every widget
- [ ] Events in ContextMenu should be managed by the subview (ContextMenuViewItems) instead of by the main view (ContextMenuView).
- [ ] Implement an API for the ContextMenu. I am thinking about an API for widgets developers to ease the menu management. For instance: addMenuItem, addMenuGroup, getGroups
- [ ] Use "Node" instead of enumerating every node when a widget wants to define a MenuProvider for every node type.
- [x] Load data trees on demand i.e. getChildren() is called when a node is selected 
- [x] Verify is getModelTree asks the server for the model tree only the first time is called. Once called, the data should be read locally.
- [x] TreeVisualiserDAT1.updateData() gives back "TypeError: Cannot set property 'undefined' of undefined"
- [x] Add method to clear content of the tree widgets, e.g. reset/remove
- [x] Add API methods to expand/collapse a given node with a parameter for how many nested level to expand? E.g. TreeVisualizerDAT1.expand(purkinje.electrical.modelTree) ?
- [x] Make input components non editable
- [x] Find a mechanism to display long description

**Comment by tarelli** [comment]
@adrianq are you happy to close this?

**Comment by adrianq** [comment]
@tarelli yes, we can close it although this subtask: "Use "Node" instead of enumerating every node when a widget wants to define a MenuProvider for every node type." would be nice to have it. It would require some kind of js inheritance (maybe related to this old issue #119) but it would definitively have some benefits. Anyway we can think about this the next time we would like to destroy geppetto and rebuild it from scratch :)
