### ISSUE TITLE
Update how 3D objects are referenced

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#263]
What we received from the server
entity.aspect.VisualizationTree.content.segment1
    We don’t receive these objects when we load a Collada file

The scene graph is something like this
VARS.scene.obj1.obj2.obj3….mesh1
These objects are created in both cases, whether we have a Collada file or whether the server is sending to the client geometries which need to be created
# Requirements
- We want to be able to univocally identify a specific three.js Object3D
  - This can be a mesh (where material transfs should be applied, as well as translations, rotations...)
  - This can be an Object3d (where translations/rotations can be applied)
- We want to be able to find a given Object3D given its identifier
- Every Object3D in the scene graph should know to what entity/aspect it belongs to
- Every Object3D needs to have a unique identifier, whether it is coming from the server or from a collada file

We should create methods like this
List<Object3D> : getAll3DObjectsForAspect(aspectInstancePath)
Object3D : get3DObjectFromAspect(aspectInstancePath, id)

Inside addDynamicVisualization if a specific Object3D is specified the transformation is applied only to that object, otherwise it is applied to every Object3D contained in the specified aspectInstancePath
# Actions
- [ ] Create getAll3DObjectsForAspect
- [ ] Create get3DObjectFromAspect
- [ ] Make sure all 3D objects have a field called geppettoId and is set
- [ ] Make sure all 3D objects have a field called aspectInstancePath and is set
- [ ] When we create 3D objects given what we receive from the server (like in hhcell for instance) we need to make sure that the geppettoId is set for the created object and that is equal to what was specified in the object coming from the server

**Comment by tarelli** [comment]
@tarelli to discuss with @jrmartin

**Comment by tarelli** [comment]
@borismarin discussed with @jrmartin here is what seems to be the best way to do this, do you see any problems with it? Once you are happy with it we can update the card.
![Design](https://www.lucidchart.com/publicSegments/view/54bff950-5c9c-4178-a127-48e60a00d7cc/image.png)

**Comment by borismarin** [comment]
In the "tomorrow" case, when you say 3D objects (inside viztree) do you
mean the Three.js objects? Because those need to
live inside the Three scene (which is currently stored in VARS.scene) in
order to be displayed.

And what about the Collada case, when the client doesn't "need" to create
any 3d object explicitly (the Collada loader does that behind the scenes).
What will be in the viztree?

**Comment by tarelli** [comment]
The 3D objects would still be added to the scene but the mapping inside VARS called meshes indexed by a string would go away. @jrmartin to confirm.
The collada case is no different, the 3D objects (the car) would still be inside entity.aspect.VisualizationTree.content.car (added to the scene of course)

**Comment by borismarin** [comment]
We would then have 2 copies of the 3d objects, one in the viztree and another in the scene?

**Comment by tarelli** [comment]
References Master Boris, references.

**Comment by jrmartin** [comment]
@borismarin Once the copy of a Three.js object/mesh/collada is created, it will be added to the VARS.scene object to be render. Also, instead of mapping to Vars.meshes as we are doing now, it will be store inside the VisualizationTree. It will be one object being added to two different places

**Comment by borismarin** [comment]
Yep master Tarelli, I was being picky about the lack of the word
"reference" in your diagram.

References Master Boris, references.

--
Reply to this email directly or view it on GitHub
<https://github.com/openworm/org.geppetto/issues/263#issuecomment-70951017>.

**Comment by tarelli** [comment]
@jrmartin will be merging this branch into widgetsimprovements and we'll test everything together there, thanks @borismarin!

**Comment by tarelli** [comment]
What was in the branch has been merged into development but I think there are still some things to do, e.g. the meshes have not moved inside the viz tree.

**Comment by borismarin** [comment]
I've left a bunch of TODO comments all over the code, which are still there after the merge. And I didn't have time to start any of the 3d ref stuff, mostly due to time invested in refactoring parts of the code which were hard to understand (removed some dead code blocks, confusing logic and even some bugs). I'm still under "paternity leave", so I won't be able to discuss the TODOs and finish this card in the near future.

**Comment by tarelli** [comment]
Obsolete, closing
