### ISSUE TITLE
Try loading C302 social sub circuit as a Geppetto sample

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#272]

**Comment by tarelli** [comment]
Improvements needed but this is now working https://live.geppetto.org?sim=https://raw.githubusercontent.com/openworm/org.geppetto.samples/master/LEMS/C302Social/GEPPETTO.xml

**Comment by gidili** [comment]
@tarelli the morphology doesn't seem to be showing up?

**Comment by tarelli** [comment]
@gidili they are on the left of the screen for some reason, see my comment, you need to move the camera around.
