### ISSUE TITLE
Highlight a core set of OSB projects with NeuroML2 files for testing on Geppetto

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#288]
While many LEMS/NML2 files are copied to https://github.com/openworm/org.geppetto.samples, it would be good to curate a fairly broad ranging list of OSB projects containing LEMS/NML2 files as test networks for Geppetto.

Initial list:

CElegansNeuroML (Multicompartmental neurons)
===============

Cell files from here:
https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/generatedNeuroML2

See https://github.com/openworm/org.geppetto/issues/344

c302 (Point neurons with connections)
==============================

LEMS files e.g.
(big) https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/LEMS_c302_A_Full.xml
(smaller, but same structure) https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/LEMS_c302_A_Pharyngeal.xml

Hay et al 2014 L5 Pyramidal cell (Large cell with lots of biophysical detail)
===========================================================

Cell: https://github.com/OpenSourceBrain/L5bPyrCellHayEtAl2011/blob/master/neuroConstruct/generatedNeuroML2/L5PC.cell.nml
LEMS sim with 1 cell: https://github.com/OpenSourceBrain/L5bPyrCellHayEtAl2011/blob/master/neuroConstruct/generatedNeuroML2/LEMS_TestL5PC.xml

ACNet2 (Small multicomp cells in small or large networks)
==============================================

Two cells: https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/LEMS_TwoCell.xml

A network with 48 exc & 12 inh cells & connections: https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/LEMS_MediumNet.xml

**More suggestions for projects welcome!**

**Comment by adrianq** [comment]
@pgleeson I have just created a [PR](openworm/org.geppetto.frontend#268) where I have added a set of tests which basically cover the models suggested in this issue.
 
Regarding CElegansNeuroML (Multicompartmental neurons) model, I have added the test but I have commented it out until #344 is solved.
