### ISSUE TITLE
Expand recording format to include visual transformations

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto#289]
We need to be able to pack visual transformations into Geppetto recordings. Adding visual transformations support will enable the Geppetto frontend to present animated 3D visualizations.

**Comment by tarelli** [comment]
@gidili Current thinking for how to do this. A new MetaType to be added. Re-use support for matrices as implemented by @jrieke. Add 3DTransformation node to the runtime tree node.
```
        c.set_time_step(0.0005, 's')
        c.add_values('muscle1.mechanical.SIMULATION_TREE.activation.', [0, 0, 0, 0, 0, 0, 0.1], MetaType.STATE_VARIABLE, False)
        c.add_values('cuticle.mechanical.VISUALIZATION_TREE.bone1.transformation', [[1, 2, 3][4, 5, 6][7, 8, 9]], MetaType.3DTransformation, True)
        c.add_values('cuticle.mechanical.VISUALIZATION_TREE.bone2.transformation', [[1, 2, 3][4, 5, 6][7, 8, 9]], MetaType.3DTransformation, True)
        c.add_values('cuticle.mechanical.VISUALIZATION_TREE.bone3.transformation', [[1, 2, 3][4, 5, 6][7, 8, 9]], MetaType.3DTransformation, True)
        #...
        c.add_values('muscle1.mechanical.VISUALIZATION_TREE.bone1.transformation', [[1, 2, 3][4, 5, 6][7, 8, 9]], MetaType.3DTransformation, True)
```

**Comment by gidili** [comment]
I've been looking at this I am thinking tasks would be:

- [ ] Add new MetaType.3DTransformation
- [ ] Add new creator class to produce HDF Geppetto recordings from SPH processed recordings that include visual transformations and simulation data. This second step is more [this other card here](https://github.com/openworm/org.geppetto/issues/292). 

One open question is where do we store the information about meshes URL. Do we need to also add a VisualEntity metatype or something like that with a path to the mesh.

**Comment by tarelli** [comment]
@gidili that information will be in the Geppetto model file not in the recording

**Comment by gidili** [comment]
@tarelli oh right, I forgot, And they get mapped via instance path. OK.

**Comment by gidili** [comment]
List of data necessary to build the recording file:

- For the cuticle for each time step
   - Transformation matrices for each bone 
- For each muscle cell for each time step
   - Transformation matrices for each bone (1 per muscle)
   - Activation signals

**Comment by gidili** [comment]
Done on https://github.com/openworm/org.geppetto.recording / see [WormSimRecordingCreator](https://github.com/openworm/org.geppetto.recording/blob/master/org/geppetto/recording/creators/wormsim.py) and test for details.
