### ISSUE TITLE
Design multi-aspect integration mechanism

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#307]
This issue captures the design of the integration across multiple aspects in Geppetto.
This will allow building a computational model which is composed by many models interacting together.
This needs to cover synchronization of the different simulations, reading outputs from one model and writing inputs to another model with the ability to specify a function which maps one value into another.
Preliminary discussions regarding this tasks happened during the OpenWorm retreat as this will allow to ultimately model in Geppetto the interactions between the electrical model of a muscle cell and its mechanical model.

![img_20141106_161112](https://cloud.githubusercontent.com/assets/81127/5072743/71129456-6e74-11e4-86ab-9af2a5f58aa3.jpg)

- [x] Review music
- [x] Review paper
- [x] Get familiar with code and architecture
- [x] Update lucidchart with high-level proposal

**Comment by tarelli** [comment]
Had a meeting today with @dkruchinin @adrianq and @borismarin. Diagram [here](https://www.lucidchart.com/documents/edit/f66e90ca-9c2d-4f16-9f79-d3f83f5d654a) for work in progress.
@dkruchinin see the checklist above to try and summarise what we said

**Comment by dkruchinin** [comment]
Small update:
* familiarised myself with music framework
* started to experiment with the code responsible for simulation in Geppetto to get better understanding of how things work

**Comment by borismarin** [comment]
And how does the music sound, @dkruchinin ?

**Comment by dkruchinin** [comment]
@borismarin Quite an advanced beast. I think we can learn a lot from it. It, as well as Geppetto, doesn't incorporate any global time management system, each application has its own clock. Ticks get synchronised either by interpolation or buffering when communication takes place. I do not get the complete picture in my head yet but I tend to think we should stick with their approach.

Besides, the way MUSIC applications communicate made me think that it might be a good idea to introduce a "message bus" into Geppetto and make it default way different aspects can talk to each other. Say, Aspect1 is configured to send a set of parameters and by default they are sent to Aspect's1 bus. If a bus has no listeners, the parameters just go nowhere. Once other aspects want to read any of the parameters, they plug themselves to the bus as listeners and start to receive data from Aspect1 (something like pub/sub model). Message receiving mechanisms may be set responsible for dealing with clock synchronisation.

**Comment by dkruchinin** [comment]
@tarelli So, my plan is:

1) Run two pendulum simulation and make them talk to each other with some useless data. The way they communicate can be hardcoded in java at first.
2) Make clock frequency of one model more dense the freq. of the other one and play with the ways they can be synchronised.
3) Replace hard-coded communication model to a configurable one (which obviously needs more discussion)

**Comment by tarelli** [comment]
@dkruchinin sounds like a good plan! Here's @borismarin pendulum btw https://github.com/borismarin/org.geppetto.samples/tree/master/LEMS/Potulum!

**Comment by tarelli** [comment]
@dkruchinin hey dan, how's progress on this?

**Comment by dkruchinin** [comment]
Documentation update:
quite a high level view on architecture: https://www.lucidchart.com/documents/edit/f66e90ca-9c2d-4f16-9f79-d3f83f5d654a/2 (I know, my drawings suck :) 

Just skim it through to get the general ideas behind my view on how the "inter aspect communication" might look like. It also briefly touches topics of ticks frequency synchronisation and suggests a way to configure the communication channels. Questions and suggestions can be found in the very end of the document.

@tarelli How far is that from what you had in mind? Is there anything I forgot to take into account?

**Comment by tarelli** [comment]
@dkruchinin Thanks Dan, great stuff! I will review the details during the weekend and leave you comments and ask questions.

**Comment by tarelli** [comment]
High level design from Dan ![Design](https://www.lucidchart.com/publicSegments/view/54f5984c-e3b4-4fbf-8e0e-40c30a0054b5/image.png)
@dkruchinin Reviewed, I left few comments and yes, it looks good, exactly what I had in mind. Let's present it at today's meeting and then let's create the next card, we'll probably have to hash out some more details in terms of class diagram/sequence diagram, we can maybe do it together in a meeting.
