### ISSUE TITLE
Integrate NSDF format for neuroscience recordings

### ISSUE THREAD

**Issue by jrieke** [openworm/org.geppetto#309]
NSDF format & API seems to complicated for now, but could be implemented in the future. 
Github repo of the API is here: https://github.com/nsdf/nsdf
Docs are here: http://nsdf.readthedocs.org/

Steps to do:
- [ ] Create a wrapper for the NSDF API that exposes the structure of ``RecordingCreator`` in org.geppetto.recording
- [ ] Create OSGi bundle for Java HDF5 Object Package, compare [scisoft-hdf repository](https://github.com/DawnScience/scisoft-hdf/tree/master/ncsa.hdf), but for a current version of HDF5. Get the jar and lib files and create the manifest and build files.
- [ ] Use this bundle to read the NSDF format in Geppetto

**Comment by tarelli** [comment]
We are adding support for NWB
