### ISSUE TITLE
Extend FunctionNode to allow conditional expresions

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto#310]
Currently when plotting some channel dynamics we got a singularity (infinite discontinuity) for some values. Therefore, the plot looks strange because some values are missing. In the org.neuroml.export we solve this problem by having conditional function. For example:

```
               if (Math.abs(fact) < 1e-4) {
            //expand around removable singularity
            return rate * (1 + fact/2);
        }
        else {
            return (rate * fact)/(1 - Math.exp(-fact));
        }
```

I don't know if this would be the best approach but I couldn't think about a better solution. Any idea @borismarin @tarelli ?

**Comment by borismarin** [comment]
What about extending _function node_ with a field _domain_, which is the range of values (of the independent variable, e.g. _v_ for the graph above) for which the expression is "valid"? this way, expressions defined by parts (LEMS `conditionalExpression`) would be mapped to multiple function nodes, each one with a different domain, which could potentially be grouped into a single _CompositeNode_.
