### ISSUE TITLE
Fix connectivity lines in C302

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#324]
Connectivity lines in C302 do not properly connect the center of the neurons.

**Comment by tarelli** [comment]
@jrmartin I spent few hours debugging this one, I found a couple of things although I haven't managed to fix the issue yet.
The spheres in a network like c302 have their position dictated by two things: the position of the vertices inside the geometry plus the position of the mesh itself. For instance RMHR has a mesh with position -265.8,-5.29,35.7 and the vertices of the sphere are also -265..etc. I tried in my local environment to set the position of the connecting lines with 
```
line.position.set(origin.x,origin.y,origin.z);
```
and now the offset is fixed but there are still problems with the color which seems to fade from green to black for instance. Also there seems to be more black lines that shouldn't be there. Do you know why is that?

Also note that I changed the following in my local:
```
geometry.vertices.push(origin.clone(), mesh.position.clone() );
```
since just passing origin and mesh.position was referencing the same vectors that were in the spheres themselves causing an update of the position for one also affecting the other (or was it intended?).
I haven't committed the two lines above as I haven't tested enough but if given the above information you might want to attempt a fix.

**Comment by pgleeson** [comment]
Having a similar problem with c302_A_Pharyngeal.nml

http://www.opensourcebrain.org/projects/celegans?explorer=https%3A%2F%2Fraw.github.com%2Fopenworm%2FCElegansNeuroML%2Fmaster%2FCElegans%2FpythonScripts%2Fc302%2Fc302_A_Pharyngeal.nml

![selection_606](https://cloud.githubusercontent.com/assets/1556687/5941323/251b99d6-a708-11e4-9887-903b49f69559.jpg)
