### ISSUE TITLE
Add display of time global variable & scale bar on x axis of plots

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#331]
Card to show time in final plot only (not to dynamically update the x axis while the plot is being populated which will require an updated plotting library)

**Comment by slarson** [comment]
Pinging this issue as it would be helpful for openworm/org.geppetto.samples#26.  Looks like it has been backlogged for a while and would also probably be helpful for WormSim

**Comment by slarson** [comment]
Curious to have a look at the underlying library to see if anyone has tried to implement this.  @jrmartin can you remind us what that library is?

**Comment by tarelli** [comment]
@slarson [flot](http://www.flotcharts.org/)

**Comment by tarelli** [comment]
Found this, might be an alternative to flot http://canvasjs.com/editor/?id=http://canvasjs.com/example/gallery/dynamic/realtime_line/

**Comment by tarelli** [comment]
Even better functionality wise although it doesn't seem particularly fast https://plot.ly/javascript-graphing-library/streaming-data/

**Comment by tarelli** [comment]
And this http://www.zingchart.com/ there's a plethora of them to try out.

**Comment by borismarin** [comment]
I had suggested plot.ly a long time ago, but it seemed to be commercial. Is that still the case, @tarelli ?

**Comment by borismarin** [comment]
BTW we can always concoct something with d3 (albeit it can be more time consuming)

**Comment by tarelli** [comment]
@borismarin unfortunately yes, it is fully featured but I can't find any source or option that doesn't say "sale". I wouldn't want to rebuild something ourselves given all there is out there.

**Comment by tarelli** [comment]
And another one, MIT licensed http://fastly.github.io/epoch/
