### ISSUE TITLE
Check if a name/reference of DAT widget exists before assigning it...

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#334]
In this session:
![selection_601](https://cloud.githubusercontent.com/assets/1556687/5814574/f5f8d1fc-a084-11e4-8ef0-541afa3f913b.jpg)

I created TreeVisualiserDAT1... TreeVisualiserDAT2... then TreeVisualiserDAT3

Then I went back and created a new DAT widget from TreeVisualiserDAT2 and it was assigned the name TreeVisualiserDAT3, the same name as an existing widget... You can see the preexisting TreeVisualiserDAT3 under the top one. Both move at the same time and you close one, you close both..

**Comment by adrianq** [comment]
I have talked to @pgleeson about this issue and I have an idea about how to solve it. Unless @jrmartin has already solved it I will assign this to me, ok?

**Comment by tarelli** [comment]
@adrianq done!

**Comment by pgleeson** [comment]
Cheers!

**Comment by tarelli** [comment]
Tested on latest dev
