### ISSUE TITLE
Extend widget framework

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#337]
- [x] Add extra configuration properties  to widgets: only one instance, widgets you can't resize, widgets that have a fixed position, etc.
- [x] All the functionality in the WidgetController can be centralized. We have a lot of redundant code

**Comment by tarelli** [comment]
@jrmartin keep in mind we have this card also, change it/update it to reflect the latest

**Comment by borismarin** [comment]
As part of #338,  I am adding
- [ ] setDraggable(true | false)
- [ ] setResizable(true | false)
- [ ] setAutoHeight(true | false )
- [ ] setAutoWidth(true | false )

**Comment by borismarin** [comment]
Why have you close that? when were the first ones done?

**Comment by tarelli** [comment]
@borismarin the second one was done some time ago but the box wasn't ticked https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/widgets/AWidgetController.js the first one was also done, when you call TreeVisualizerDAT1.registerEvent(Events.Select) the widget starts acting as a singleton, as in the same instance is reused as you click on different cells which was the idea, you did the resize part.
