### ISSUE TITLE
Check text on geppetto.org main website on Linux

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#339]
On my Ubuntu machine the main Geppetto website looks like this:

![selection_158](https://cloud.githubusercontent.com/assets/1556687/5840868/84b034ec-a190-11e4-9090-0b7d2b2c50e2.png)

and this:

![selection_159](https://cloud.githubusercontent.com/assets/1556687/5840880/9e173822-a190-11e4-87ad-8612aaf0e2c9.png)

i.e. text v pale & hard to read. 

Also there are many recent nice screenshots floating about for the Gallery...

**Comment by pgleeson** [comment]
On Firefox btw...

**Comment by tarelli** [comment]
@pgleeson tested on Firefox on both Mac and Ubuntu and can't reproduce!
