### ISSUE TITLE
Check full OpenWorm NeuroML model on Geppetto/OSB

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#344]
The 302 cell multicompartmental model is taking very long to load on OSB: 
http://www.opensourcebrain.org/projects/celegans?explorer=https%3A%2F%2Fraw.github.com%2Fopenworm%2FCElegansNeuroML%2Fmaster%2FCElegans%2FgeneratedNeuroML2%2FCElegans.net.nml

I haven't tried it on OSB/Geppetto in a while but this used to load in about a minute. This model should ideally be used regularly to (stress) test Geppetto.

**Comment by tarelli** [comment]
@pgleeson was the model fully ported to NML2? I remember the connections were still using the old style and this was never tested because of that, definitely a good test and one we want to consider.

**Comment by pgleeson** [comment]
The neuroConstruct project's [in a much more up to date state now](https://github.com/openworm/CElegansNeuroML/issues/20), including fully generated NeuroML 2 files. There are a range of networks there now for testing:

**[20 Pharyngeal cells only, no connections](http://www.opensourcebrain.org/projects/celegans?explorer=https%3A%2F%2Fraw.github.com%2Fopenworm%2FCElegansNeuroML%2Fmaster%2FCElegans%2FgeneratedNeuroML2%2FPharyngealCellsOnly.net.nml)**
Works for me, but slow to load

**[20 Pharyngeal cells only, & ~250 connections, electrical & chemical](http://www.opensourcebrain.org/projects/celegans?explorer=https%3A%2F%2Fraw.github.com%2Fopenworm%2FCElegansNeuroML%2Fmaster%2FCElegans%2FgeneratedNeuroML2%2FPharyngealNetwork.net.nml)**
Works for me, but v. slow to load

**[302 cells only](http://www.opensourcebrain.org/projects/celegans?explorer=https%3A%2F%2Fraw.github.com%2Fopenworm%2FCElegansNeuroML%2Fmaster%2FCElegans%2FgeneratedNeuroML2%2FCellsOnly.net.nml)**
Still waiting for it to load....

**[The Big Kahuna: 302 cells, 6465 chem syns, 1847 electrical syns](http://www.opensourcebrain.org/projects/celegans?explorer=https%3A%2F%2Fraw.github.com%2Fopenworm%2FCElegansNeuroML%2Fmaster%2FCElegans%2FgeneratedNeuroML2%2FCElegans.net.nml)**
Not too hopeful at the moment...

@tarelli  @adrianq @jrmartin, the challenge has been set...

**Comment by tarelli** [comment]
No wonder this is very slow at the moment, the model with all the connections is 50MB, for this to work decently we need to complete the instance/type refactoring (https://github.com/openworm/org.geppetto/issues/335) which is ongoing.
The reason why it used to load in a minute is because we were not extracting the synapses information which we are doing now.
In case you don't want to wait for it to load here's a screenshot for now :)

![screen shot 2015-02-03 at 13 44 09](https://cloud.githubusercontent.com/assets/81127/6021115/26d4d2f4-abab-11e4-9e36-d84ceadae7bd.png)

**Comment by pgleeson** [comment]
Nice pics...

Isn't the current CElegans.net.nml just 2.3MB? This scale of network (<10,000 synapses) is certainly something that Geppeto should aim to handle quite easily. I suspected that the problem was down to the synapses loading and the instance/type refactoring issue.

**Comment by tarelli** [comment]
Considering all the cells and synapses it gets to 7MB (which is amount of information loaded by the server) plus the redundancy introduced by the lack of "types" makes it explode to 50MB (amount sent from the server to the client).

**Comment by tarelli** [comment]
That's not true, I considered also other networks in there, probably total size is close to 3MB top.

**Comment by tarelli** [comment]
@jrmartin test with this:
```
Simulation.loadFromContent('<?xml version="1.0" encoding="UTF-8"?><tns:simulation xmlns:tns="http://www.openworm.org/simulationSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../../main/resources/schema/simulationSchema.xsd"><tns:entity><tns:id>CElegans</tns:id><tns:aspect><tns:id>electrical</tns:id><tns:simulator><tns:simulatorId>neuroMLSimulator</tns:simulatorId></tns:simulator><tns:model><tns:modelInterpreterId>neuroMLModelInterpreter</tns:modelInterpreterId><tns:modelURL>https://dl.dropboxusercontent.com/u/7538688/celegans.nml?dl=1</tns:modelURL></tns:model></tns:aspect></tns:entity></tns:simulation>')
```

**Comment by pgleeson** [comment]
Not quite... there is still an issue with c302 models which are generally named of the form: c302_C_Pharyngeal.nml (i.e. not *.net.nml, as they can contain networks+cell+new types). This means they are put in the Other menu on Explore model. 

For some reason models loaded in this way, even though they have a simulatable model, throw an error. This is posibly due to the experiment settings not getting correctly initialised:

![selection_122](https://cloud.githubusercontent.com/assets/1556687/19491271/5059332c-956a-11e6-90fb-70a7868f3358.png)

Look [here](http://www.opensourcebrain.org/projects/celegans?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252FCElegansNeuroML%252Fmaster%252FCElegans%252FpythonScripts%252Fc302%252Fexamples%252Fc302_C_Pharyngeal.nml#). [This renamed version](http://www.opensourcebrain.org/projects/celegans?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252FCElegansNeuroML%252Fmaster%252FCElegans%252FpythonScripts%252Fc302%252Fexamples%252Ftemp_test%252Fc302_C_Pharyngeal.net.nml#) can be used to run simulations.

**Comment by tarelli** [comment]
@pgleeson yeah that's a problem on the OSB side of things though rather than the cElegnas model per se which works (and I'm adding as a sample). OSB doesnt generate an experiment properly if it's just a .nml. Something we should fix 👍

**Comment by tarelli** [comment]
@pgleeson I managed to simulate this from OSB (although maybe no inputs in the model?) What error were you getting? What were the other models were you had path problems? Thanks!

![screen shot 2017-01-10 at 15 50 25](https://cloud.githubusercontent.com/assets/81127/21813084/f75d300a-d74c-11e6-931c-9a4a57c4ff21.png)

**Comment by pgleeson** [comment]
A number of the examples listed under "Other", i.e. they don't end with *.net.nml are problematic. See c302_C_Pharyngeal.nml. This may be to do with being under Other rather than the relative paths problem. c302_D_Pharyngeal.nml does have a path, but not ".."

See [here](http://opensourcebrain.org/projects/pospischiletal2008?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FPospischilEtAl2008%252Fmaster%252FNeuroML2%252Fcells%252FRS%252FRS.net.nml#) for an example with: include href="../../channels/Kd/Kd.channel.nml", etc.
