### ISSUE TITLE
Reduce widgets to icons

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#345]
Add ability to
- [x] Reduce a widget to icon
- [ ] Reduce a widget to its toolbar
- [x] Maximize a widget

**Comment by borismarin** [comment]
http://romb.github.io/jquery-dialogextend/example.html

**Comment by tarelli** [comment]
@anishshah101 feel free to move the card to the in progress column once you start working on it!

**Comment by borismarin** [comment]
Maybe [snapping](https://jqueryui.com/resources/demos/draggable/snap-to.html) could enter into this card as well?

**Comment by tarelli** [comment]
@anishshah101 are you still planning to work on this? Any way I can help? Thanks!
