### ISSUE TITLE
Define interactions between the converter service and the external process simulator

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#347]
- [ ] Produce a sequence diagram for this

**Comment by tarelli** [comment]
@adrianq @jrmartin I will organize a meeting this week to discuss this

**Comment by tarelli** [comment]
Started on this https://www.lucidchart.com/documents/edit/441da30d-df65-4001-8809-2a796c80460b/6

**Comment by pgleeson** [comment]
Should this be publicly accessible? Logged in and can't get to it...

**Comment by tarelli** [comment]
![diagram](https://www.lucidchart.com/publicSegments/view/54d34cd5-be44-41fd-805b-63660a004324/image.png)
Yeah I should have pasted the image, all contributors have access, you should be able to see the Geppetto folder with your gmail account.
