### ISSUE TITLE
Decide on how to create Geppetto recordings from Geppetto

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#348]
The main two options are either calling the Python code that exists from inside Geppetto or use Java binding for HDF5 library.
The downside of using Python would be relying on Python being installed, relying on a script and potentially impacting performance.
The downside of using a Java binding for HDF5 is that we have to create such binding as it currently [doesn't exist](https://github.com/DawnScience/scisoft-hdf/issues/2).

**Comment by tarelli** [comment]
[This](https://github.com/DawnScience/scisoft-hdf/tree/master/ncsa.hdf/META-INF) exists to attempt what we need (wrapping of HDF-JAVA). It is three years old and it doesn't use Maven but it could be a starting point.

**Comment by jrmartin** [comment]
I'm checking out that sample for the bindings, and updating it to latest hdf5 library. Also making it an OSGI bundle.
