### ISSUE TITLE
Fix Frontend issues

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto#352]
- [x] Optimize create Runtime Tree client side, it takes 20 seconds for c302. 
- [x] Fix camera for particle system, don't have geometries like all other meshes
- [x] Fix select command for Entity, different than clicking in scene since an entity like c302 can reference many meshes in the scene. I.E. There's no mesh for c302, but a bunch of meshes for subentities
- [x] The octocat is now moving everytime you open/close the console
- [x] Try to figure out a direction vector for the camera. This will rotate the camera to give the "best view" of the scene.
- [x] update qunit tests in widgetsimprovement to match up with events framework
- [x] Duplicates three.js vendor
- [x] Merge development and 3drefs branch into widgetsimprovement
- [x] Fix connectivity lines to take visual reference nodes into account otherwise, if they are not present, use the position of the mesh instead of the center of the bounding box
- [x] Fix time (global time to match simulator time)
- [x] Restart simulation restarts recordings too
- [x] TreeVisualizer widget not updating with new values
- [x] Test get model tree
- [x] Time node instead of var
- [x] Test branch and merge into development

**Comment by tarelli** [comment]
@jrmartin Can updateTags just be called as a once off at the end after all objects are created?

**Comment by jrmartin** [comment]
Yeah, but it might take just as long to loop through the whole objects created. I'll need to debug it more, I don't fully trust the profile tool in the console. I removed calls to updateTags locally, and it's still taking about the same time to load c302, except profile just says time is spent idle.
