### ISSUE TITLE
Create Geppetto recording from JAVA

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#357]
- [x] Get familiar with [org.geppetto.recoring](https://github.com/openworm/org.geppetto.recording/tree/master/org/geppetto/recording/creators), [docs](http://docs.geppetto.org/en/latest/recordingandreplaying.html)
- [x] Create a class in org.geppetto.core that offers an equivalent API, the API will be used to turn RAW data into a Geppetto recording file that can then be stored and streamed
- [x] Add unit tests
- [x] Use create approach
- [x] Add time_step and time methods, populate time array
- [x] Add value to existing variable adds another value, don't update it replacing old data
- [x] aspectsubtree and composite metatypes

**Comment by jrmartin** [comment]
@adrianq @tarelli I committed these changes to Dev, class TestConvertDATToRecordingClass has an example on how to use the converter class. One thing I forgot to asked during the meeting this morning, where in the DAT are we storing the unit measurement?

**Comment by adrianq** [comment]
maybe @pgleeson can answer this question?

**Comment by pgleeson** [comment]
All of the saved variables in the DAT files are in SI units. The generated code for e.g. NEURON must save the voltage etc. in SI even though it uses mV internally etc. To see what dimension the data is, you need to relate the quantity in the Lems Simulation/OutputFile element to the original variable/parameter in the Lems/NeuroML2 file and get the correct dimension from that.
