### ISSUE TITLE
Check pendulum simulation still works

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#362]

**Comment by tarelli** [comment]
@dankruchinin https://raw.githubusercontent.com/tarelli/org.geppetto.samples/patch-2/LEMS/Potulum/GEPPETTO.xml this will work in the latest from dev. @borismarin I forked your pendulum to update it with the latest. Now theta1 is plotted, the collada doesn't seem to appear but I haven't looked into it.

**Comment by tarelli** [comment]
@dkruchinin see above, used wrong nick

**Comment by borismarin** [comment]
Do you need the collada stuff for your tests? It's not supposed to work
before we (well, I) finish #263...

**Comment by tarelli** [comment]
@borismarin no, all @dkruchinin needs is for the simulation to run, which now does!

**Comment by borismarin** [comment]
As I've suspected. Just erase the collada line then, I'd be surprised if
the LEMS part of the model had ever stopped working...

**Comment by tarelli** [comment]
@borismarin it was a matter of updating the script and some backend code that was assuming that a NeuroML doc was there in some of the refactorings that happened, all good now, no need to remove anything!
