### ISSUE TITLE
Add console option to change background colour from black in main 3D view

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#364]
Or is it there already?

**Comment by pgleeson** [comment]
Any update on this? Will be required for making nice screengrabs for posters, papers, presentations etc...

**Comment by gidili** [comment]
@pgleeson in the meanwhile you can change line 87 and 96 manually --> https://github.com/openworm/org.geppetto.frontend/blob/datamanager/src/main/webapp/js/GEPPETTO.Init.js#L87 :dancers:

**Comment by tarelli** [comment]
I propose G.setBackgroundColour(colour) this would be an easy one to add.

**Comment by gidili** [comment]
@tarelli @pgleeson I was touching stuff around there so I threw it in --> https://github.com/openworm/org.geppetto.frontend/commit/b2f3cbf3cf609fa1751b6f3671601fb5cf84f853

Moving this item in review till somebody else can test.

**Comment by gidili** [comment]
Example: 

<img width="1237" alt="screenshot 2015-07-10 18 49 01" src="https://cloud.githubusercontent.com/assets/68134/8625248/7c7a898c-2735-11e5-8752-602c9829e1a8.png">

**Comment by pgleeson** [comment]
@gidili thanks for adding that!
