### ISSUE TITLE
Add attribute to Geppetto to optionally specify what to load

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#366]
[This](http://www.opensourcebrain.org/projects/grancelllayer?explorer=https%3A%2F%2Fraw.github.com%2FOpenSourceBrain%2FGranCellLayer%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FGranCellLayer.net.nml) is a nice example for testing the connectivity visualisation, but there is an [extra Golgi (large) cell](https://github.com/OpenSourceBrain/GranCellLayer/blob/master/neuroConstruct/generatedNeuroML2/GranCellLayer.net.nml#L52) on the bottom right:

![selection_623](https://cloud.githubusercontent.com/assets/1556687/6601510/f20bee7a-c80d-11e4-9f2f-34c810e9c809.jpg)

The network visualised with all connections in neuroConstruct:

![selection_624](https://cloud.githubusercontent.com/assets/1556687/6601534/164053b2-c80e-11e4-9cf3-5f838f1b45a8.jpg)

**Comment by tarelli** [comment]
I am not wrong the NeuroML file includes both a cell and a network, there is no target like in LEMS that specifies that the entry point is the network so both things are visualised. @pgleeson @adrianq we discussed this some time ago if I remember correctly.

**Comment by pgleeson** [comment]
I see what you mean (In fact there are 3 cell instances in the nml, and all 3 are probably shown at the bottom left corner, it's just the large golgi cell that's obviously misplaced). This is probably an issue for any nml network with cells & a network specification...

Would it make sense to have at the Geppetto level an optional attribute which is the id of a target element in a generic model which is what should be loaded/displayed? This can be non NeuroML specific; many model files in different formats may contain lots of elements in one file. Geppetto interprets the whole model, maps it to internal representations (along with assigning ids) and if target_id is missing, everything gets displayed, otherwise only the selected element.

**Comment by pgleeson** [comment]
Another example of this.. [This project](http://www.opensourcebrain.org/projects/olfactory-bulb-network-model-o-connor-angelo-and-jacob-2012) has a net with 6 detailed cells and should look something like 

![6cells](http://www.opensourcebrain.org/attachments/download/92/Mitral_Cell_Model.png)

but gets an extra 6 cells at the origin...

![screen shot 2015-03-19 at 09 11 23](https://cloud.githubusercontent.com/assets/1556687/6727304/d1ad1878-ce18-11e4-8c3e-22f5e717f6dc.png)

**Comment by pgleeson** [comment]
![selection_636](https://cloud.githubusercontent.com/assets/1556687/7087160/16b755be-df80-11e4-8a2a-3b78881f4bc5.jpg)

![selection_637](https://cloud.githubusercontent.com/assets/1556687/7087184/4b2ab16a-df80-11e4-983e-fd32a0bbafd1.jpg)

Screenshots from example: PCISPH small elastic/liquid scenes, after play is pressed. Is this related to above..?

**Comment by tarelli** [comment]
Nope this is a bug introduced by the features refactoring I believe. @jrmartin can you check the floating particle? It's probably one not updated by the dynamic feauture due to some index offset?

**Comment by tarelli** [comment]
@pgleeson thanks for testing this btw!

**Comment by tarelli** [comment]
Added business rule in NeuroML model interpreter to take care of this.
```
		//Business rule: If there is a network in the NeuroML file we don't visualize spur cells which 
		//"most likely" are just included types in NeuroML and are instantiated as part of the network
		//populations
```
