### ISSUE TITLE
Extend plotting widget to allow the user the see the entire result of a simulation

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#370]
- [x] Allow for downsampling https://github.com/sveinn-steinarsson/flot-downsample/ depending on size of the widget
- [x] Allow to add more than one result at once
- [x] Allow to switch between two modes: current one with a fixed number of time steps where old values get deleted when there are too many, new one change the sampling to display all the available timesteps (potentially downsampled, see first point)
- [x] Update documentation

**Comment by pgleeson** [comment]
+1
