### ISSUE TITLE
Integrate code to enable collaba based animations into org.geppetto.frontend

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto#373]
We need to integrate prototype code from [skeletonExtraction](https://github.com/openworm/skeletonExtraction/tree/master/ClientSide/examples) repo to enable collada based animations in the [Geppetto frontend bundle](https://github.com/openworm/org.geppetto.frontend).

- [x] Branch org.geppetto.frontend to add the ability (optional) to set a custom renderer, see [this](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/GEPPETTO.Init.js#L73)
- [x] Add a component to the wormsim (in a branch of org.wormsim.frontend) that includes the modified renderer, see [here](https://github.com/openworm/org.wormsim.frontend/tree/master/src/main/webapp/js/components/dev)
- [x] Use the added method (point 1) inside the implementation of the added component
- [x] Deploy the new component to org.wormsim.bower (see [documentation](http://docs.geppetto.org/en/latest/components.html))
- [x] Manual check that the custom renderer is instantiated and used
- [x] Create the two pull requests

**Comment by gidili** [comment]
@tarelli gonna need your help to structure subtasks for this as checkboxes (we'll split cards if the subtasks are big enough).

**Comment by gidili** [comment]
hey @mihairaulea can you point me to the pull requests?

**Comment by tarelli** [comment]
@gidili @mihaiaulea I need a PR to review

**Comment by mihairaulea** [comment]
i know. i am wrapping up the worminfo flow. i will get back asap.
