### ISSUE TITLE
An automated testing framework to test the contents of Geppetto model visualisations

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#374]
**Goal**

Automated tests that can check whether given models are returned correctly from the live Geppetto (or OSB) server.

**Motivation**

It's not possible to check every Geppetto (or OSB) model which should run/display correctly manually every day or even before each release. New features/updates may lead to slowing down or breaking of existing models which should work. Creating this test framework will help spot these issues sooner

**Possible method**

A script is created that can be run regularly & reads a config file containing a list of URLs/links to Geppetto scripts/models which *should* display correctly if loaded in a browser from the live server.

The script knows what elements/widgets etc. should be accessible if the model is interpreted correctly and uses Javascript to check the presence of these & compare to expected values.

A log is kept of the load time and any errors or delays longer than a specified time are reported.

**The challenge**

How to implement this... It's a general problem though, how to test that a given url returns an expected result in a given time. Something like this perhaps: http://www.seleniumhq.org/ or http://dalekjs.com/index.html? Ideally the script should test with real browsers, as some issues have been reported in Firefox only etc.

**Comment by tarelli** [comment]
@pgleeson https://live.geppetto.org/GeppettoTests.html We already have QUnit tests that check the whole stack, see the link. As you can see we are already checking some models there, the tests can be expanded in order to check more things like attributes etc. but the current infrastructure we have is I believe adequate. Those tests are executed every time we release. Thoughts?
![screen shot 2015-03-30 at 19 40 59](https://cloud.githubusercontent.com/assets/81127/6903814/b53ebb88-d714-11e4-95ac-f39a5efd7dc8.png)

**Comment by adrianq** [comment]
I think QUnit is the proper framework for this. I have added some [tests](openworm/org.geppetto#288) to the Geppetto QUnit (see [PR](https://github.com/openworm/org.geppetto.frontend/pull/268))

**Comment by pgleeson** [comment]
Yes, this is just the kind of thing that's needed. Will try to add more examples from OSB to the tests. Cheers.

**Comment by tarelli** [comment]
Thanks @adrianq for adding more coverage!

![screen shot 2015-04-10 at 12 17 36](https://cloud.githubusercontent.com/assets/81127/7086671/aa10897a-df7b-11e4-8917-94126b86bab0.png)

**Comment by pgleeson** [comment]
All (new) tests passing locally here too. Thanks guys.

![selection_638](https://cloud.githubusercontent.com/assets/1556687/7087370/a4b673d4-df82-11e4-90cd-f05a69d7acc1.jpg)
