### ISSUE TITLE
Refactor run simulation workflows

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#376]
See sequence diagram [here](https://www.lucidchart.com/documents/edit/441da30d-df65-4001-8809-2a796c80460b/6) and [here](https://www.lucidchart.com/documents/edit/4c3283a4-527c-cb68-bb8d-14570a009e11/1). Experiment design [here](https://www.lucidchart.com/documents/edit/373b1d9b-ca5d-4bc1-a2cb-bd96a6646370/1)

The backend will receive a command to run an experiment.  Experiments that the user decides to run get queued. The ExperimentsRunManager is in charge of holding the list of all the queued experiments and is in charge to trigger their execution when all the conditions are satisfied. ExperimentRun will be created to manage the execution of a single experiment. 

- [x] Create an ExperimentsRunManager to manage the experiments as they get queued, as they start running etc. 
    - [x] Manage the different statuses of an experiment and the creation of ExperimentRun
    - [x] Manage concurrency (multiple users will be queuing experiments at the same time)
- [x] Create ExperimentRun     
    - [x] Iterate over the AspectConfiguration and SimulatorConfiguration for the given experiment and instantiate all the SimulatorServices/ConversionServices
    - [x] Once a simulation is completed persist all the results in the DB/S3 (Matteo)
- [x] Refactor SessionContext to remove all the references that won't disappear anymore when the session is closed, i.e. remove the session independent artefacts. (Dan)
- [x] Update the diagrams with whatever changes happened during the implementation
- [x] Refactor ServletController, MessageInbound (Matteo)
- [x] Add missing methods to IProjectManager (Matteo)
    - [x] newExperiment
    - [x] setWatchedVariables
    - [x] setParameters
- [x] Add missing implementations to ProjectManager
    - [x] loadExperiment (Dan)
    - [x] runExperiment (Dan)
    - [x] deleteExperiment
    - [x] persistProject
- [x] Implement RuntimeExperiment.release() (Dan)
- [x] Implement ExperimentRun.release() (Dan)
- [x] Implement ExperimentRun.run() (Matteo)
- [x] Implement ExperimentRun.storeResults() (Matteo)
- [x] Implement ExperimentRun.endOfSteps() (Matteo)
- [x] Implement ExperimentRun.stateTreeUpdated() (Matteo)
- [x] Implement ExperimentRunManager.checkExperiment() (Matteo)
- [x] Remove SimulationService (Dan)
- [x] Remove SessionContext (Dan)
- [x] Resolve user workflows (guest, logged in, authenticated, security)
    - [x] Check GeppettoManager gets always the same instance for all the entry points (Websocket, Login, getProject servlets etc) for a given session and a different one for different sessions (Dan)
    - [x] Guest users can be many, distinguish them, every GeppettoManager (and we have one per session) needs to have a different user (Dan). 
    - [x] The user ideally should always be set through the Login servlet. (It is set by the UserResource servlet actually now) (Dan)
    - [x] How to grant secure access to an user? Shiro? -> The login servlet which already exists should
save in the session who is the current user.
    - [x] Add IUser to ProjectManager interfaces (Dan)

RESOLVED: 
ExperimentsRunManager will have a lifecycle associated to Geppetto, it gets created when Geppetto is initialized and it gets destroyed when Geppetto is. ExperimentRun will have a life cycle linked to the execution of the Experiment, when an Experiment is ready to be executed ExperimentRun is created and all the services required to execute the experiment are instantiated.
OLD:
To figure out: what is the life cycle of the ExperimentController? At the moment we have a SessionContext whose life cycle reflects the state of the user connection with the server, i.e. if a user connects to Geppetto a SessionContext starts to exist, if a user disconnects SessionContext is destroyed.
Is the ExperimentController instead a sort of a singleton for the whole Geppetto? 
Note we cannot have an ExperimentController attached to SessionContext because the controller will have to survive also once the session has been closed. Do we need something like a usercontext? A place which contains all the instances of the instantiated services (that won't have to go away anymore when the session is closed but rather once the simulation of a particular experiment is over) and potentially the ExperimentController.

**Comment by tarelli** [comment]
@ddanny see updated design [here](https://www.lucidchart.com/documents/edit/373b1d9b-ca5d-4bc1-a2cb-bd96a6646370/1), red comments are "wrong paths" there for reference. I'm sure you'll have questions, I've setup a meeting tomorrow morning to go through it!

**Comment by ddanny** [comment]
I didn't get any meeting invitation.
