### ISSUE TITLE
Error Code: INITIALIZATION

### ISSUE THREAD

**Issue by vindicadi198** [openworm/org.geppetto#380]
Stack Trace:

org.geppetto.simulation.visitor.PopulateVisualTreeVisitor
org.geppetto.core.model.ModelInterpreterException: java.lang.NullPointerException

Error occurred when loading one of my NeuroConstructs exported NML2 models. The generated files were modified by hand to change the URLs to work with the hosting I am using to test Gepetto.

The link to my simulation file is : http://218.248.6.155/Ex6_CerebellumDemo/generatedNeuroML2/aditya.xml

**Comment by tarelli** [comment]
@vindicadi198 Can you try clicking on the link below and tell me if you see the sphere?
https://live.geppetto.org/?sim=http://218.248.6.155/Ex10_NeuroML2/generatedNeuroML2/aditya.xml
See screenshot for what I get:

![screen shot 2015-04-08 at 10 45 05](https://cloud.githubusercontent.com/assets/81127/7044421/305741aa-ddeb-11e4-9458-963949040ac0.png)

I added the tree widget manually with the following commands on the console once the file was loaded:

```
net.electrical.getModelTree()
G.addWidget(3).setData(net)
```
