### ISSUE TITLE
Figure out why dev AWS crashes

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto#381]
AWS for development keeps crashing, log.log don't show any errors about a crash, last log is a successfull update sent to client.

**Comment by jrmartin** [comment]
Got the server to run again after restarting AWS instance. Still crashing, but I can see issue now. 


OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000da9eb000, 54128640, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 54128640 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/jvm-2926/hs_error.log

**Comment by tarelli** [comment]
Ok good to know, we are looking at expanding the instances, when we'll do that this will be taken care of.
