### ISSUE TITLE
OutOfMemoryError running Geppetto

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#383]
With the latest development branches I'm getting an error when I run Geppetto locally and try to load the ACNet example:

![selection_635](https://cloud.githubusercontent.com/assets/1556687/7086733/3cc3ad6a-df7c-11e4-835c-f698dc142555.jpg)

Is there a need/recommended way to change the max allowed memory for virgo/geppetto? Wasn't required before...

**Comment by tarelli** [comment]
@pgleeson when starting from command line in the file \bin\dmk.sh there are the following lines:        
JAVA_OPTS="$JAVA_OPTS \
                    -Xmx512m \
                    -XX:MaxPermSize=512m"
in live.geppetto we are using the following settings (hasn't changed in a long while)
        JAVA_OPTS="$JAVA_OPTS \
                    -Xmx1024m \
                    -XX:MaxPermSize=512m"

**Comment by pgleeson** [comment]
Thanks. That worked. A bit strange that it worked fine on my machine before and is just giving errors now.
