### ISSUE TITLE
Error in connectivity widget for ACNet

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#384]
![selection_640](https://cloud.githubusercontent.com/assets/1556687/7087895/c783deb0-df87-11e4-9c96-01512e9202fe.jpg)

Selecting a green square should highlight 2 small cells (basket cells) as this is an inhibitory-inhibitory connection. 2 pyramidal cells are selected instead.

Using latest development version locally. On live.geppetto.org it works fine...

Any recent changes @adrianq?

**Comment by adrianq** [comment]
No really. I couldn't think about any change which could has an impact on this. Maybe @jrmartin or @tarelli can shed some light on this...

**Comment by pgleeson** [comment]
Verified this is fixed in the latest development version
