### ISSUE TITLE
SetParameters backend implementation

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#385]
To be done in the DataManager branch
- [x] Meet with @ddanny to know the lay of the land in the branch
- [x] Make sure latest of development is merged into the DataManager branch
- [x] Add method to ISetParameterFeature ```setParameter(Map<String,String>)```
- [x] Add mapping between Geppetto runtime nodes and NeuroML/LEMS object when they are created as part of populateModelTree
- [x] Implement SetParameterFeature for LEMS and NeuroMLModelInterpreter. The implementation will use the map created at point three to resolve the original object and change the value of the parameter. 
- [x] Write JUnit tests to cover the mapping functionality and the change of parameters
- [x] Add method to message inbound to setParameter and implement the code which ends up calling the newly added feature and persisting the parameters in the database under the appropriate AspectConfiguration
-  [x] Add code to check if a model interpreter supports the ISetParameterFeature before using it, return an error to the client otherwise

**Comment by jrmartin** [comment]
The AspectConfiguration is still not part of datamanager branch, second to last item was done using a visitor with comments to replace with code using AspectConfiguration
