### ISSUE TITLE
SetParameters frontend implementation

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#386]
- [x] Implement setValue method in the ParameterSpecificationNode. The method will call the added functionality in the server. The server will respond with either an error or a PARAMETERS_SET message which confirms the value of the set parameters.
- [x] Add QUnit tests to check the setParameters functionality
- [ ] Perform a setParameters prior to execute a NEURON simulation and verify the simulation is affected

**Comment by jrmartin** [comment]
Closing card, but since datamanager branch can't be run, testing a Neuron simulation with set parameters is not possible for last item.
