### ISSUE TITLE
Error in display of cell positions

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#388]
A [simple network](https://github.com/OpenSourceBrain/Cerebellum3DDemo/blob/master/neuroConstruct/generatedNeuroML2/Cerebellum3DDemo.net.nml) with test cells ([soma only](https://github.com/OpenSourceBrain/Cerebellum3DDemo/blob/master/neuroConstruct/generatedNeuroML2/ShapedCellSoma.cell.nml), [simple dends](https://github.com/OpenSourceBrain/Cerebellum3DDemo/blob/master/neuroConstruct/generatedNeuroML2/ShapedCell.cell.nml)) was created in NeuroML2. This displays correctly in neuroConstruct (all axes are 100um):

![selection_641](https://cloud.githubusercontent.com/assets/1556687/7157734/3b2ea490-e36a-11e4-831c-197388dd5893.jpg)

but there are some issues with display in Geppetto (on OSB):

![selection_642](https://cloud.githubusercontent.com/assets/1556687/7157769/bac116a2-e36a-11e4-9762-542d20968ad7.jpg)

Bottom left cell is the "ghost" cell that appears (actually both cells) at the origin currently when visualising NML2 networks (https://github.com/openworm/org.geppetto/issues/366). Cells seem to be placed at the correct relative locations and all 3D dendrites are correct, though the 3D positions seem to be x2 larger than they should be...

**Comment by pgleeson** [comment]
Seems to be a recently introduced issue, compare gran cell network at start of #366:

![selection_623](https://cloud.githubusercontent.com/assets/1556687/6601510/f20bee7a-c80d-11e4-9f2f-34c810e9c809.jpg)

and now:

![selection_643](https://cloud.githubusercontent.com/assets/1556687/7159032/29502336-e377-11e4-9341-4c9ffc0fd007.jpg)

**Comment by tarelli** [comment]
@jrmartin I bet this is related to the features changes

**Comment by jrmartin** [comment]
@tarelli I'll take a look, but might be it.

**Comment by jrmartin** [comment]
@pgleeson Are those issues also on live.geppetto.org? Or only in development branch?

**Comment by pgleeson** [comment]
I've only tested it with the OSB visualiser, which is the last release of Geppetto.

**Comment by jrmartin** [comment]
@tarelli Looks like this is a  pre-features bug since it's on last release as well.

**Comment by pgleeson** [comment]
This is an issue in ACNet too (and has been for a while...)

![selection_646](https://cloud.githubusercontent.com/assets/1556687/7184542/ba5f2aaa-e455-11e4-9c43-b52edd6d4ff9.jpg)

![selection_645](https://cloud.githubusercontent.com/assets/1556687/7184553/c21a71e6-e455-11e4-8f64-96b85682274e.jpg)

**Comment by pgleeson** [comment]
Latest development version installs & runs fine on my machine. This is still an issue though; every NeuroML2 network with positioned cells is currently displaying incorrectly... Would be great to get this sorted by OSB meeting.

**Comment by jrmartin** [comment]
Issue is fixed, can be seen in latest development branch

**Comment by pgleeson** [comment]
Excellent! Verified locally...

![selection_649](https://cloud.githubusercontent.com/assets/1556687/7429218/e0c82088-eff5-11e4-8811-11e82140a7d7.jpg)

Here's another snazzy screenshot (of [this network](https://raw.githubusercontent.com/OpenSourceBrain/Cerebellum3DDemo/master/NeuroML2/CerebellarCortex.net.nml)) as a reward...

![selection_650](https://cloud.githubusercontent.com/assets/1556687/7429271/acef1694-eff6-11e4-82a8-354ade4fc310.jpg)

Let's get this live!

**Comment by gidili** [comment]
Looking great!
