### ISSUE TITLE
Update Conversion Services code in data manager branch

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#394]
Post merge with data manager
- [x] Extend IConversionService interface to receive also AspectConfiguration (this is on the datamanager branch)
- [x] Extend LEMSConversionService to use the AspectConfiguration to generate the simulation block which will result in having the variables specified in the configuration recorded

**Comment by adrianq** [comment]
Done. Pending issues to be discussed with @tarelli:
- [ ] We can assume there is going to be length and step. Currently I am reading it from the simulation component in the lems file
- [ ] If there is not a Target and Simulation Component. Are we going to generate it? If so, how are we going to extract the target component? 
- [ ] Although we can have multiple aspectconfiguration associated to an experiment. I am assuming there is going to be a single aspect configuration. Can this be a problem in the short term?

**Comment by adrianq** [comment]
@tarelli @ddanny At the moment we have a timestep attribute in the SimulatorConfiguration table/java bean. Shall we add a length (simulation time) as well? or should we store this parameter inside the 'parameters' hashmap in the SimulatorConfiguration?

**Comment by tarelli** [comment]
We should add it, feel free to do so, just a variable in the class
