### ISSUE TITLE
Gather requirements to upload data to external services

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#396]
We need to be able to upload data (models, simulation results, etc.) to DropBox and Figshare, i.e. the user will link their DropBox and/or Figshare account (if they have one) and from that moment they'll be able to push to it models and results of their simulation

- [x] Learn DropBox API to upload files and gather what is required for the user to link its account with the Geppetto one
- [x] Learn FigShare API to upload files and gather what is required for the user to link its account with the Geppetto one 

For both we need to understand:

- [x] What is their linking procedure?
- [x] Do we need to store the tokens in the the database for each user that has linked their account
- [x] What is the Geppetto API that will allow to link to the accounts?
- [x] Where / how will we expose it?

Prototype

- [x] Prototype in a new branch two classes that will allow to push some data to both.
```IExternalUploadService with methods to link/unlink/upload(URL file, ...)
DropboxUploadService and FigShareUploadService```

**Comment by jrmartin** [comment]
@tarelli After a day of looking into both more, couldn't find any Java api for FigShare, not many tutorials either. Dropbox api is quite straightforward. I'll be adding prototype directly to datamanager branch since I'll be moving to it next, don't think a new branch is needed for it.

**Comment by jrmartin** [comment]
![dropboxview](https://cloud.githubusercontent.com/assets/4562825/7527262/6e6940de-f4ce-11e4-9104-51a5054fd0cc.png)

Branch in core upload-data has this prototype.
