### ISSUE TITLE
Add axis helper to Geppetto

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#397]
A scaled axis helper that can be added through the console
- [ ] `G.showAxisHelper(boolean)`

**Comment by pgleeson** [comment]
Is this currently enabled? Doesn't work on OSB...

**Comment by pgleeson** [comment]
Sorry, just saw that the issue is still open...

**Comment by tarelli** [comment]
An addition to this card from @robbie1997 is to also add the option to rename the axis label to support different orientations (cartesian, anatomical, etc.)

**Comment by tarelli** [comment]
https://github.com/openworm/org.geppetto.frontend/blob/9a651cdbc74940e91f6b0e8812536c96093a207c/src/main/webapp/js/GEPPETTO.js#L378

**Comment by pgleeson** [comment]
@tarelli still not seeing this in the console... should it be enabled with either

    G.showAxisHelper(true)

or 

    G.setupAxis()

**Comment by pgleeson** [comment]
Should still be added at some point...

**Comment by mattearnshaw** [comment]
`Canvas1.engine.setupAxis()` works, @tarelli can better comment whether another interface is appropriate…

**Comment by tarelli** [comment]
I'd just add a wrapper at the Canvas level as we do for most methods (engine is meant to be an internal and interfaces there can change) Canvas.showAxis(boolean) probably would do.

**Comment by mattearnshaw** [comment]
https://github.com/openworm/org.geppetto.frontend/pull/726

**Comment by pgleeson** [comment]
These should be 100um long ideally (maybe print some info on the axis length & colours once the command is called). Currently they seem to be 200um long, see https://github.com/OpenSourceBrain/SpineShowcase/blob/master/NeuroML2/Example1.net.nml, cells are 100um long:

![image](https://user-images.githubusercontent.com/1556687/35042464-bc291860-fb80-11e7-9970-947ff66a00e0.png)
