### ISSUE TITLE
Fronted/Backend workflows for the data manager branch Part 1

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#399]
Workflows

- [x] Update GeppettoServletController to call interfaces from the [ProjectManager](https://github.com/openworm/org.geppetto.core/blob/datamanager/src/main/java/org/geppetto/core/simulation/IProjectManager.java)

Loading of the projects
- [x] Rename LOAD_SIMULATION/INIT to LOAD_PROJECT
- [x] 	Make the messages homogeneous loadfromurl/loadfromid/loadfromcontent
       ```
        LOAD_PROJECT_FROM_URL("load_project"), 
	LOAD_PROJECT_FROM_ID("init_id"), 
	LOAD_PROJECT_FROM_CONTENT("init_sim")
       ```
- [x] Populate the backbone objects when a Project is loaded (Populate both the Project object and the experiments)
- [x] Add loadExperiment to InboundMessages and ConnectionHandler
- [x] When loadExperiment is called return the runtime tree for it (equivalent of the old LOAD_MODEL)
```
PseudoCode:
			RuntimeTreeRoot runtimeTree=geppettoManager.loadExperiment(requestId, experiment, project);Project(requestID, geppettoProject);
			String serializedTree=runtimeTree.apply(SerializeTreeVisitor)
			websocketConnection.sendMessage(requestID, OutboundMessages.EXPERIMENT_LOADED, serializedTree);
```
- [x] Use GSon to serialize the IGeppettoProject/IExperiment models

Run of an experiment
- [x] Hook up the javascript run method in Experiment with the server API call to run an experiment
- [x] Notify the client when the simulation is completed (the backbone objects are updated, e.g. getStatus() would return COMPLETED)
- [x] If the user tries to run an experiment which is already COMPLETED an error is returned

Play a completed experiment
- [x] API method for the Experiment object, it sends a command to the server that returns the simulation results associated with it (it sends the recording, same as what we do with the external simulators). An option allows to let the user decide whether to play the experiment step by step (a la jLEMS) or altogether (a la ExternalSimulator).
    - [x] An event play_experiment is triggered at the end of this command (whether we just got the values from the server or whether we already had the values). If any widget will be open and they know how to act on the play_experiment event they will do so. Plotting widget will plot the data when the play_experiment event is received. The triggered event can have an option which specifies if to play it step by step or show the entire results at once.
- [x] Add a timer thread in Javascript which is in charge of sending events for an experiment that is being played (start event, update events and stop event). The widgets (and everything else in Geppetto) will be reacting to these events in the same way as they are doing today when these events are instead generated because of messages received from the server.

Switch experiments
- [x] Hook up the javascript setActive with the server API loadExperiment
- [x] Add API to the server to set an experiment as active

Persist a project
- [x] Add Project Node and Experiment Node to server
- [x] Add method to persist a project (cannot be undone for now), it requires adding the API to the server and to the Project backbone object

Delete an experiment
- [x] Add method to an experiment to Delete it (Confirmation dialog), it requires adding the API method to the server and to the Experiment  backbone object

Note: Once all the workflows are taken care of the Simulation backbone object will not be needed anymore as all the current APIs will move to either Project or Experiment
- [x] Move existing APIs into Project backbone object or into the Experiment
- [x] Delete Simulation backbone object

**Comment by jrmartin** [comment]
Question.Will the Observer and Multiuser mode still play a role in datamanager?  Both implement ISimulationCallbackListener, could be combined into one if modes are of no use for projects/eperiments

**Comment by tarelli** [comment]
I was discussing this with @gidili today, probably observer mode "as is" will go away. But I want to think some more about this looking at the code, will let you know asap.

**Comment by tarelli** [comment]
@jrmartin @ddanny @gidili @adrianq Recap.
What Geppetto has at the moment is a way to run the simulations in realtime while the user is connected, the results are streamed to the client as they are processed. We are calling these realtime (or synchronous) simulations.
We are adding to Geppetto the ability to deal also with asynchronous simulations which run without being coupled with the user connection. The workflows in this case are different: the user indicates that they want to run one or more simulations (called experiments). An experiment might be executed right away or later on depending on the server queues and load. The user might still be connected or might have closed the browser, this won't have an impact on the run of the simulation.
The only thing that will happen, when a simulation is completed, is that the simulator will notify the `ExperimentRunThread` through the `ISimulatorCallBackListener` interface that the simulation is completed, this will in turn trigger storing the HDF5 results into the S3 bucket

- [ ] Add implementation to `endOfSteps` inside `ExperimentRunThread` to store the recording results into S3. Modify `endOfSteps`to have a parameter which will point to the URL of the results of the simulation. 

We are adding a mechanism for the client to pull from the server the status of the experiments, in the dashboard this mechanism will happen through a Spring Rest service, in the simulation environment through the websocket connection. 

- [ ] Add pull mechanism to the websocket environment
- [ ] Add pull mechanism to the dashboard environment
- [ ] Add pull mechanism server side to respond to both

If the client receives the information that an active experiment is now completed the client will automatically ask the server to send the results with the play command

- [ ] Modify the play command for an Experiment client side so that if results are already available in the client we just play them, if they are not (this scenario above) it will ask the server to send the results.
What will happen at this stage is that the server will look in the database, open the simulation results (an HDF5 Geppetto recording) contained in an aspect configuration and will start streaming it to the client.
*Note*
Support for synchronous simulations will be temporarily dropped. An implementation will be added in the near future to add to the PCISPHSimulator and jLEMSSimulator that we currently have to store their results in an HDF5 Geppetto recording so that then we will be able to use them asynchronously.

**Comment by tarelli** [comment]
@jrmartin 
When calling setActive on an experiment the server needs to:
- [ ] Look inside each AspectConfiguration for a given experiment, for each variable in either the "watchedVariable" or in the "modelParameter" list we need to add them to the runtime tree and set their flags ("watched" for instance) and values accordingly.
Note that neither getSimulationTree or getModelTree are called so far but the subset of variables that were stored inside an experiment are added to the runtime tree nonetheless. When getModelTree or getSimulationTree will be called eventually (if the user ever will) will have to take into account the already existing nodes and not overwrite them.

**Comment by tarelli** [comment]
@jrmartin In the previous version of Geppetto the fact that we were showing an animation step by step (jLEMS, SPH) or all at once (NEURON) was due to the fact that we were receiving from the server either the updates step by step, in the first case, or all together, in the latter case. In the new version of Geppetto for now we'll always have all the steps from the beginning after calling playExperiment, i.e. the server will always send the entirety of the recorded simulation. In this new version the user will still be able to see the results (both on widgets and on the 3D canvas) step by step or all at once (by passing different options to the playExperiment method) but this time rather than having the events START, UPDATE...UPDATE...UPDATE, STOP coming from the server they will be generated by a thread in javascript that handles the playing. This will enable us to visually have the same results as before but working with data that is already client side. This will also enable us for instance to loop in the cycle from timestep 0 through the last one and back to the first one and so on. Note that the playExperiment method will ask the server to send all the results only the first time, once the results are received all subsequent calls to playExperiment will only result on starting/stopping the client thread since all the data is already there and there's no need for the server to send it again. cc @gidili

**Comment by tarelli** [comment]
- [ ] If status is not completed show error
- [ ] Add flag per experiment (remember to clean it when we switch experiment) that says wether we have values or not
- [ ] If the user sends play command after the first time don't ask the server
- [ ] Play_Experiment and Update_Experiment are the same event just with different parameters
- [ ] Have the widget handle Experiment_Over and Update_experiment
- [ ] Make sure that when an event play experiment is triggered the plotting widget always starts from a clean state
- [ ] Assess performance of web worker

**Comment by jrmartin** [comment]
Only thing missing from this, is using pull mechanism from dashboard, bit confused about it after looking at code. Moving it to dashboard review.
