### ISSUE TITLE
Review 50

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#402]
- [x] Fix setIdleTimeout
- [x] Matteo. If there is one or more network in the root of the NeuroML file don't add entities for the sibling cells (as they are "most likely" cells that instantiated inside the network). This is a problem of the populateVisualTree most likely.
- [x] Selection of a spur cells doesn't go away when then selecting an entity inside another entity
- [x] Autocomplete doesn't show entities anymore

**Comment by jrmartin** [comment]
Can someone with safari check if the issues with slow loading of hhcell simulation happens? It all points out it slows down in Firefox because opening jquery dialogs in that browser is much slower thatn Chrome and IE, wondering if safari is same

**Comment by tarelli** [comment]
Just checked, Safari is slower than Chrome but in a different way, it takes longer to load and appear but no discontinuities.

**Comment by jrmartin** [comment]
My part on this card is done, factored out firefox issues into new one. Selection of spur cells will go away once second issues is gone.
