### ISSUE TITLE
Firefox improvements

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#403]
- [ ] Scrollbar for the console in Firefox is ugly

**Comment by sujeet14108** [comment]
![screenshot from 2016-02-29 14 22 49](https://cloud.githubusercontent.com/assets/9781422/13389706/01d97134-def0-11e5-9c3a-9cb8d548b888.png)
Are you talking avbout the scroll bar on the rightmost side?

**Comment by tarelli** [comment]
@sujeet14108 it was about the scrollbars in the Javascript console, not in the dashboard, however they must have updated firefox and it looks reasonable right now, see image below:
<img width="1349" alt="screen shot 2016-03-03 at 12 43 45" src="https://cloud.githubusercontent.com/assets/81127/13494680/aaa18a14-e13d-11e5-93e0-743df35019b7.png">
