### ISSUE TITLE
More specific errors when simulation file cannot be loaded

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto#406]
At the moment we show a "Invalid simulation file" for almost any error related to a problem loading the simulation file. For instance, when there is not internet connection

**Comment by tarelli** [comment]
Duplicate of https://waffle.io/openworm/org.geppetto/cards/553b641e76bf160d00c6ab13

**Comment by tarelli** [comment]
https://github.com/openworm/org.geppetto.frontend/issues/281
