### ISSUE TITLE
Implement a communication mechanism between Geppetto and any other website

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto#407]
In OSB every time the user wants to load a model we load Geppetto in an iframe and load the simulation file. We do this even if Geppetto is already loaded. It would be nice just to execute sth like ```Simulation.load("https://raw.githubusercontent.com/OpenSourceBrain/ACnet2/master/neuroConstruct/generatedNeuroML2/MediumNet.net.nml")``` for instance. Obviously try to get the iframe and execute any js script command leads into a cross domain error.

I was having a look at this https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage as a good option to solve the problem. It looks like a nice way of creating a tunnel between Geppetto and any other web.

**Comment by pgleeson** [comment]
Also it would be good to be able to construct a direct URL just pointing to the NeuroML file (as opposed to requiring a GEPPETTO.xml for example), so:

https://live.geppetto.org/?modelInterpreterId=neuroMLModelInterpreter&modelURL=https://raw.githubusercontent.com/openworm/org.geppetto.samples/master/NeuroML/ACnet2/MediumNet.net.nml

for example, or the equivalent on the OSB visualiser...

**Comment by tarelli** [comment]
@adrianq +1
@pgleeson the Geppetto file will be always required to configure the environment, the experiments, the views etc. A NeuroML document is one of the models that could be associated to an aspect.

**Comment by adrianq** [comment]
A prototype can be found in this [PR](https://github.com/openworm/org.geppetto.frontend/pull/334)

**Comment by adrianq** [comment]
Created another [PR](#36) with CORS implementation for embedded environments.
