### ISSUE TITLE
Polish Dashboard

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#410]
[Mockup reminder](https://docs.google.com/drawings/d/1G57X74SeZLD89XxInQlB7QtDUSAqdTdrUxUc5wwyxM0/edit)

- [x] Remove spurious elements (Profile link at the top, gap at the bottom)
- [x] Finalise Login behaviour with both persisted bundle and without
    - [x] If the persisted bundle is deployed if there is a User logged in show the user in the top right corner, again no option to logout (since we are not directly managing the login for now we won't manage the logout either). If there is no user logged in the dashboard is not populated.
- [x] Make sure all relevant information is visualized, e.g. Experiments, etc.
- [x] Put placeholder icons inside projects, geppetto symbol?
- [x] Now that we are using the ID enable double click to open a project
- [x]  Add ability to open directly an experiment &experiment=id this will result in experiment.setActive in the simulation environment
- [x] When resizing the window the projects stop being squares and sometimes the layout is wrong (few empty slots in a row)
- [x] Remove white gap
- [x] Fix instance path vs local instance path (instance path should be displayed also for models)
- [x] Fix alignment issues (the 0, the details button when the tile is too long, anything else you might see)
- [x] User current user name in ProjectCollection instead of guest in order to retrieve user projects
- [x] Test cross-browser

**Comment by borismarin** [comment]
Why Polish? I prefer Italian.

**Comment by gidili** [comment]
I prefer Filipino

**Comment by tarelli** [comment]
@ddanny the gaps in a row are still there btw
![screen shot 2015-06-01 at 15 46 45](https://cloud.githubusercontent.com/assets/81127/7922481/647d56e8-08a4-11e5-8efd-968648fab9e6.png)

**Comment by borismarin** [comment]
Such elegant asterisks...

**Comment by adrianq** [comment]
A hippie with some dreadlocks would be cooler....

**Comment by tarelli** [comment]
Gaps issue happens only on Mac, fun...

**Comment by tarelli** [comment]
- [ ] The white gap is still there if the window is tall enough
![screen shot 2015-06-09 at 12 25 06](https://cloud.githubusercontent.com/assets/81127/8056699/8d7922bc-0ea2-11e5-9a5d-524424e7d22c.png)
- [ ] The button on the top right corner should open the project same as double click
- [ ] Deleting a project should open a confirmation dialog (Yes/No) no other tab should be open if the user presses yes
