### ISSUE TITLE
Finalise setParameters

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#412]
- [x] Verify the parameters are getting changed in the NeuroML object model not only in the runtime tree model
- [x] Update parameters in the LEMS model
- [x] Add code for parameters to be saved in the AspectConfiguration
- [x] Verify the parameters are saved in the AspectConfiguration
- [x] Verify when switching to an Experiment with parameters set that the values in the runtime tree are updated. Verify that switching back to an experiment with other parameters or no parameters the tree is once again updated.
- [x] Test functionality of setParameters with run of simulation. Verify parameters had effect on the simulation output
- [x] Allow tree visualizer widget to change value of ParametersNode. This results in a API call

**Comment by tarelli** [comment]
@pgleeson 
```
		while(it.hasNext())
		{
			String newValue = it.next();
			AValue value = new DoubleValue(Double.valueOf(parameters.get(newValue)));
			ParameterSpecificationNode node = modelParameters.get(newValue);
			node.getValue().setValue(value);
			
			//retrieve NeuroML object instance associated with param node
			Object instance = this.getObjectsMap().get(node);
			//retrieve setter method from instance associated with param node
			Method method = (Method) this.getMethodsMap().get(node);
			
			//Lems lemsDoc=(Lems) model.getModel(ServicesRegistry.getModelFormat("LEMS"));
			// Parameter p= lemsDoc.getComponent(arg0).getParameter()
			// p.setValue(value);
			
			try {
				//invoke setter method passing instance and new value
				method.invoke(instance, value.toString());
			} catch (Exception e) {
				throw new ModelInterpreterException(e);
			}
		}
```
See the commented lines in the middle, the class is [this one](https://github.com/openworm/org.geppetto.model.neuroml/blob/datamanager/src/main/java/org/geppetto/model/neuroml/services/NeuroMLModelInterpreterService.java#L632), just a snippet that works elsewhere is enough, what we have is:
 * neuroml object containing the parameter 
 * name of the parameter
What we need is 
 * Corresponding LEMS parameter object

**Comment by pgleeson** [comment]
@tarelli @adrianq See here: https://github.com/NeuroML/org.neuroml.export/blob/16284a22f817ce13ad4f58a5bc68add5e63fd687/src/test/java/org/neuroml/export/utils/UtilsTest.java#L98 for an example of parsing NML & LEMS object models and setting values in each of the data trees & some of the helper methods needed.

**Comment by tarelli** [comment]
@pgleeson @adrianq thanks for the help, it's working with this example (basket cell from acnet2) see [this](https://github.com/openworm/org.geppetto.model.neuroml/blob/1d9908b58d3fee5d070874a6ee41125d2a4118f1/src/main/java/org/geppetto/model/neuroml/services/NeuroMLModelInterpreterService.java#L657) and [this](https://github.com/openworm/org.geppetto.model.neuroml/blob/1d9908b58d3fee5d070874a6ee41125d2a4118f1/src/main/java/org/geppetto/model/neuroml/utils/LEMSAccessUtility.java#L91) which I had to add to find a component that could have been anywhere, not just at the root level. As soon as Boris is done all of this code will have to go away, these are the kind of things that shouldn't happen. 
The unit test is [here](https://github.com/openworm/org.geppetto.model.neuroml/blob/1d9908b58d3fee5d070874a6ee41125d2a4118f1/src/test/java/org/geppetto/model/neuroml/test/NeuroMLModelInterpreterServiceTest.java).
