### ISSUE TITLE
Test experiment workflows

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#414]
- [x] Add unit tests to check creation operations on the different entities using the DBManager (for instance creating a new experiment, etc.)
- [x] Add unit tests to check update operations on the different entities using the DBManager (for instance updating the status of an experiment, etc.)
- [x] Add uni test to check storing of results on S3 and linking them to the DB through a PersistedData object
- [x] Make sure we have coverage and comments for all the methods inside DBManager
- [x] Test Delete of a project

**Comment by ddanny** [comment]
I cannot install neuron, please assign this ticket to somebody else.

**Comment by ddanny** [comment]
experiment.setParentProject() is not being set in the persistence case
