### ISSUE TITLE
Add support for LDAP/OAuth2

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#415]
- [ ] Identify required information to connect to an LDAP or OAuth2 provider
- [ ] Create connector for LDAP/OAuth2 configured through a spring bean with a CREATE_USER_IF_NOT_EXISTING parameter. The idea is that there is nothing specific to external providers outside of the spring configuration.
- [ ] Test that the connector works (access is granted or denied) depending on whether an external provider has a logged in user or not and that the IUser from the Geppetto DB is resolved correctly.

**Comment by adrianq** [comment]
To keep in mind: http://stackoverflow.com/questions/6730522/how-to-send-parameter-to-iframe-with-a-http-post-request

**Comment by adrianq** [comment]
Moving this issue to done.  Finally we went for a different approach. Anyway something like this should be implemented in the future but we will open a new card for that task
