### ISSUE TITLE
Make Geppetto symbol into SVG file and add it to custom font

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#417]
https://github.com/borismarin/org.geppetto.frontend.icons
- [ ] Move custom font project to openworm organization?
- [ ] Make SVG for Geppetto symbol
- [ ] Add Geppetto symbol to custom font

**Comment by borismarin** [comment]
Would you like to revamp the logo or should it be kept the same
minimalistic asterisk?

**Comment by borismarin** [comment]
Done
http://rawgit.com/borismarin/org.geppetto.frontend.icons/master/gpt/gpt-icons-preview.html

**Comment by tarelli** [comment]
@borismarin sorry I missed the comment, remember to mention me so I get a notification! I still like it btw this is the logo!
![geppettosymbol](https://cloud.githubusercontent.com/assets/81127/7912980/de517120-0863-11e5-9959-741d3e9074d8.png)

**Comment by borismarin** [comment]
If you want to tweak it, go to svg/originals/gpt_logo.svg (the icons only
"work" if we convert stroke to path, and it gets hard to edit them after
doing that). Then, select all, "object->stroke to path", and save it under
svg. (inkscape)
I'll make it "fatter", as per your svg.

**Comment by adrianq** [comment]
@borismarin Can you make a good looking hippie with dreadlocks? I would love to have my own icon...

**Comment by tarelli** [comment]
![](http://www.widmannsrl.com/wp-content/gallery/hippies/hippie-dude-wig.jpg)

**Comment by adrianq** [comment]
hahahaha but...where are the dreadlocks? the good looking hippie? and the svg!!!!

**Comment by borismarin** [comment]
@tarelli done; please verify
http://rawgit.com/borismarin/org.geppetto.frontend.icons/master/gpt/gpt-icons-preview.html

**Comment by tarelli** [comment]
@borismarin perfect, thank you!
