### ISSUE TITLE
Support for multi-compartment neuronal simulation

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#418]
- [x] Test running of multi-compartment simulation, e.g. Purkinje cell using LEMSConversionService and NEURON
    This will result in multiple variables recorded, one per each segment, e.g. S1V, S2V, etc.
- [x] Test with ACNet

**Comment by pgleeson** [comment]
Is replay of simulation results, with different colours per segment, enabled?

**Comment by pgleeson** [comment]
Just saw https://github.com/openworm/org.geppetto.frontend/issues/311...
