### ISSUE TITLE
Streaming of recording

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#423]
Since the datamanager branch we decoupled execution of a simulation and streaming of its results. Now when a simulation is executed a recording is created. This recording is at the moment sent naively to the client all at once while it would probably be best to stream the recording and having the client building the entire simulation results as a consequence of a number of updates. This is desirable especially since simulation results could be arbitrarily big.

**Comment by ashishkadam** [comment]
Where would I find the concerned files to make these changes?
