### ISSUE TITLE
Problem loading live.geppetto.org on Firefox

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#428]
On Ubuntu:

![selection_233](https://cloud.githubusercontent.com/assets/1556687/8700559/5d9f70ea-2b04-11e5-9269-8310f1b11613.png)

**Comment by tarelli** [comment]
@pgleeson whaaat, same here, looking into it. Just what we needed: browser dependent SSL issues :)

**Comment by tarelli** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=587407

**Comment by tarelli** [comment]
Fixed disabling weak ciphers in the server.

**Comment by pgleeson** [comment]
@tarelli, works for me now. Thanks for fixing this so quickly.
