### ISSUE TITLE
Broken links...

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#429]
URLs like this don't work anymore...

https://live.geppetto.org/?sim=https://raw.githubusercontent.com/openworm/org.geppetto.samples/pg_samples/obj/TVB/GEPPETTO_cortex.xml

**Comment by gidili** [comment]
The path changed, the root brings you to the dashboard, you have to add a geppetto to make it work:
```
https://live.geppetto.org/geppetto?load_project_from_url=[YOUR_LINK]
```
But careful, it now needs to be a link to a Geppetto project (json).

**Comment by pgleeson** [comment]
So is there not any URL I can construct from an 'old' Geppetto simulation xml file? 

https://live.geppetto.org/geppetto?load_project_from_url=https://raw.githubusercontent.com/openworm/org.geppetto.samples/pg_samples/obj/TVB/GEPPETTO_cortex.xml doesn't work... 

Something i can put on the README here: https://github.com/openworm/org.geppetto.samples/tree/pg_samples/obj/TVB

**Comment by tarelli** [comment]
It's enough to create a simple project.json that points to those models, I can send you a template @tarelli.

**Comment by gidili** [comment]
@pgleeson @tarelli but that .xml file needs to change slightly based on the new schema too
