### ISSUE TITLE
Add support for electrophysiology data

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#431]
See https://github.com/openworm/org.geppetto/issues/430 for adding support for experimental data.
This card in particular wants to track adding support for electrophysiology data.
Currently there are different existing formats to analyse and evaluate:

 * [Neurodata Without Border (NWB)](https://crcns.org/NWB). The Allen Brain Institute has an SDK to work with this [here](http://alleninstitute.github.io/AllenSDK/).
 * [NIX](https://github.com/G-Node/nix/wiki)

And the [Neo](http://neuralensemble.org/neo/) library which could (should?) be used as a proxy to access the different formats.

**Comment by tarelli** [comment]
@stripathy @nicain @rgerkin @mpsonntag @adrianq @apdavison Let's have the discussion here, please feel free to mention and bring in to the conversion anybody else who should be involved so that this can be a community effort as much as possible. I would also like to setup a meeting on Hangout next week to discuss, would that work for folks?

**Comment by stripathy** [comment]
I have a nice ipython notebook showing an example of getting data from the Allen Institute ephys dataset in NWB format here: https://github.com/stripathy/AIBS_cell_types/blob/master/Allen_ephys_playground.ipynb

Let's get Christian Kellner (@gicmo) who helped develop NIX in on this conversation too.

**Comment by rgerkin** [comment]
That works for me.  I'd also like to mention that the OpenWorm ChannelWorm repo has digitized a lot of current traces from e.g. IV curve experiments, and it has a Django interface for pulling these data out into Python objects.  For example, look at cell 4 [here](https://github.com/openworm/ChannelWorm/blob/master/tests/SCU_IVCurve_Model.ipynb).  The `GraphData.objects.get` part is using the Django ORM to grab some data and put it into a current array and a voltage array.  I think they have something similar for a few actual current and voltage traces.

**Comment by rgerkin** [comment]
But the Allen data might be a better place to start.  @stripathy and I can write a module to go from a brain area or cell type to the corresponding current trace for a specific sub-experiment (e.g. a specific train of voltage pulses), so there would be an easy entry point for getting traces corresponding to the cell of interest.  @tarelli I'm available over the next 4 days for a hangout, but will be unavailble for about a week starting on Tuesday afternoon.

**Comment by gicmo** [comment]
Hi everyone and thanks a lot @stripathy for bringing me in. There is an exhaustive documentation for [C++](http://g-node.github.io/nix/) and [python 2+3](http://g-node.github.io/nixpy/). The latter includes a [tutorial](http://g-node.github.io/nixpy/tutorial.html) that also shows of our tagging features and metadata support. We have support for [Matlab](https://github.com/G-Node/nix-mx) and since this summer also [Java](https://github.com/G-Node/nix-java). 
@asobolev is working on a NEO backend already. Additionally there is a [demo repo](https://github.com/G-Node/nix-demo) which contains some IPython Notebooks and actual ephys data converted to the NIX format, e.g. NWB's [pvc-6](https://github.com/G-Node/nix-demo/blob/master/NWB%20pvc-6%20use-case.ipynb), [pvc-7](https://github.com/G-Node/nix-demo/blob/master/NWB%20pvc-7%20use-case.ipynb). NB: the little plot class (`Plotter`) to creates the correct plots, including axis labels from the data stored inside the NIX files. We (also @jgrewe and @stoewer) would be happy to work with you guys.

**Comment by pgleeson** [comment]
This might be quite relevant for accessing large data sets in HDF5 in distributed locations: http://bolt-project.org/docs/index.html.

Count me in on a hangout...

CC @ccluri & [NSDF](https://github.com/nsdf/nsdf)

**Comment by tarelli** [comment]
@pgleeson cool, note there's this card https://github.com/openworm/org.geppetto/issues/309 which is tracking NFDS, I didn't include it here since it's more about simulation results rather than experimental ones.

**Comment by tarelli** [comment]
<a target="_blank" href="https://www.google.com/calendar/event?action=TEMPLATE&tmeid=YmRrZTdydXBhdmlwcmprMjZiZmhvN2g4azQgYnF2bHJtNjQybTNpcmplaGJldGhva2tjZGdAZw&tmsrc=bqvlrm642m3irjehbethokkcdg%40group.calendar.google.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_en-GB.gif"></a> This is the meeting event for Monday before Rich goes away, does it work for folks interested in joining? If not I can create a doodle poll.

**Comment by ccluri** [comment]
Thanks for including. I will try to join this hangout as an audience.

**Comment by tarelli** [comment]
@stripathy @nicain @rgerkin @mpsonntag @adrianq @apdavison @ccluri @jgrewe @stoewer a reminder the meeting will be on Hangout (link on the event) in 50 minutes for those interested to join!

**Comment by ccluri** [comment]
Perhaps I am missing something, I do not see a link on the google calendar page for the hangout. Correct link please?

**Comment by stripathy** [comment]
here is the link: https://plus.google.com/hangouts/_/calendar/YnF2bHJtNjQybTNpcmplaGJldGhva2tjZGdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.bdke7rupaviprjk26bfho7h8k4?authuser=0

**Comment by tarelli** [comment]
[Minutes](https://docs.google.com/document/d/1QHsFNmZU_4O7pOnXpTEAU9HjpXnhn5wE6Dx8grXhWpo/edit) from today's meeting, thanks everyone for joining!

**Comment by pgleeson** [comment]
Paper relevant for all this: http://www.sciencedirect.com/science/article/pii/S0959438815000756

**Comment by pgleeson** [comment]
Also, have you seen this: http://biojs.net/

**Comment by tarelli** [comment]
@pgleeson thanks! Yes I've seen biojs before, it looks quite cool, I see many potential widgets there, do you know anybody involved?

**Comment by pgleeson** [comment]
Sorry, don't know anyone at biojs...

**Comment by stripathy** [comment]
Here's the updated documentation for NWB:

·        [Documentation and code](https://neurodatawithoutborders.github.io/) have been added to publicly accessible repositories on Github

·        [Exemplar data sets in the NWB format](https://crcns.org/NWB/exemplar-data-sets) can be downloaded from CRCNS

·        Neurodata Without Borders web site, http://nwb.org, is now online 

I also mentioned this activity to one of the NWB project leaders at Allen Institute - hopefully we can get some buy in from them.

**Comment by tarelli** [comment]
Thanks @stripathy will review!

**Comment by stripathy** [comment]
There'll be an info session on the NWB data format at the SFN conference in Chicago: http://alleninstitute.org/news-events/events-training/event/society-neuroscience-2015 (Sunday Oct 18). One of the topics to be discussed will be next steps for NWB, including getting the format adopted. If others in this thread are interested in attending, perhaps we can further discuss this there.

**Comment by tarelli** [comment]
Thanks @stripathy I won't be at SfN but @pgleeson and @slarson might be able to attend!

**Comment by tarelli** [comment]
Will be coordinating with @rgerkin adding support for this in the coming months. Rick do you have a tentative starting date yet?

**Comment by rgerkin** [comment]
@tarelli I am in the process of hiring an ASU computer science graduate student for this.  Someone should hopefully be ready to contribute in the coming weeks.

**Comment by rgerkin** [comment]
@matteo I'd like to welcome @niteshthali08 to the group.  He is an ASU master's student who will be working on this issue.  He'll officially start next week.  What is the preferred documentation entry point for developers?

**Comment by rgerkin** [comment]
@tarelli I'd like to welcome @niteshthali08 to the group. He is an ASU master's student who will be working on this issue. He'll officially start next week. What is the preferred documentation entry point for developers?

**Comment by tarelli** [comment]
@rgerkin great! Welcome onboard @niteshtali08! The docs for developers is here http://docs.geppetto.org/en/latest/devdocs.html The first thing is setting up the development environment, I recommend installing Eclipse Luna for this http://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/lunar (we have few blog posts with additional help for that http://blog.geppetto.org/). Nitesh why don't you join the next Geppetto meeting next Tuesday at 4pmGMT? If you send me an email I'll add you to the calendar invite.

**Comment by tarelli** [comment]
@nicain this will be for NWB support to Geppetto, I don't know David's Github account if you can ping him as well :)

**Comment by niteshthali08** [comment]
Thanks @tarelli. I will join the upcoming meeting. My email id: nthali@asu.edu 
Could you please add me to the Calendar invite ?

**Comment by nicain** [comment]
David, what is your github user name?

Best,
-n

**Comment by tarelli** [comment]
Some great progress from @niteshthali08 

<img width="1543" alt="screen shot 2016-04-12 at 17 51 52" src="https://cloud.githubusercontent.com/assets/81127/14580472/da4ee612-03c5-11e6-91d7-5237b2a41657.png">

**Comment by niteshthali08** [comment]
Plot for data from another sweep.
<img width="1280" alt="screen shot 2016-04-17 at 5 56 25 pm" src="https://cloud.githubusercontent.com/assets/4617921/14591399/bdc54c88-04c5-11e6-90a6-43a39f2537fb.png">

**Comment by LordKrabo** [comment]
@niteshthali08 @tarelli Added to sprint 75.

**Comment by tarelli** [comment]
First NWB sample added to geppetto 0.3.0 [link](https://live.geppetto.org/geppetto?load_project_from_id=18). Closing this card capturing additional improvements in separate cards.
