### ISSUE TITLE
Store Linked Dropbox id in DB

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto#439]
Once user gives Geppetto permission to upload to Dropbox, an id or token needs to be stored in DB to avoid asking user again to grant permissions

**Comment by tarelli** [comment]
The token is getting stored after using the link command. All persistence tests passing, including the upload ones:
![screen shot 2015-10-09 at 15 10 06](https://cloud.githubusercontent.com/assets/81127/10396005/f32ad92a-6e97-11e5-8e04-ee770dfe0eac.png)
