### ISSUE TITLE
Design multiple-aspect integration protocol

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#440]
Minutes from meeting [here](https://docs.google.com/document/d/141U1LmSOXPby-fZKTJiK3V1VwPN5T-ig2LKRv-aqORI/edit)
- [ ] Look at the [MUSIC](http://www.springerlink.com/content/r6j425027lmv1251/) protocol and evaluate whether to reuse it or not. [Sources](http://software.incf.org/software/music/music/music_1.0.7.orig.tar.gz/at_download/file)

```
if(!MUSIC)
```
- [ ] Define set of messages that are used to communicate with the external processes, i.e. PROTOCOL
- [ ] Identify intermediate technology to communicate with the external processes, e.g. 0MQ or MPI, etc.

```
endif
```

**Comment by LordKrabo** [comment]
Added to sprint 75 @tarelli

**Comment by tarelli** [comment]
We looked at this and put together a proposal for GSoC 2016 with Mikael Djurfeldt (the MUSIC author) to have some help but nobody has applied, moving to the backlog for now. I think @dkruchinin bandwidth has also trickled down a bit?:)
