### ISSUE TITLE
unSelectAll leaves selected cell transparent

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#456]
To reproduce:

Go here: http://www.opensourcebrain.org/projects/pyloricnetwork?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FPyloricNetwork%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FPyloricPacemakerNetwork.net.nml

Select one cell

Type: G.unSelectAll()

![selection_752](https://cloud.githubusercontent.com/assets/1556687/10427053/0391676e-70de-11e5-801d-edada635b319.jpg)

**Comment by tarelli** [comment]
@pgleeson I fixed many selection related bugs this release, let's test this again as soon as that's integrated

**Comment by pgleeson** [comment]
Have the development branches installed on my laptop now. This is fixed.

**Comment by pgleeson** [comment]
Btw @tarelli is it intentional that when a cell is selected now that the connected cells don't go partially transparent..? A bit harder to see the original cell...
