### ISSUE TITLE
More informative status strings

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#457]
e.g. what is status DESIGN?

![selection_756](https://cloud.githubusercontent.com/assets/1556687/10427160/139d4c30-70df-11e5-997e-42256ae36ef7.jpg)

**Comment by tarelli** [comment]
Does the documentation help? http://docs.geppetto.org/en/latest/usinggeppetto.html

**Comment by pgleeson** [comment]
The string itself should say more than just DESIGN: e.g. "The experiment is persisted and in the design state. It is editable, it is possible to select which variables are going to be watched when the experiment will run and set model/simulation parameters associated with it."

The more info the better for the user...

**Comment by tarelli** [comment]
I see, we could add another enumeration [here](https://github.com/openworm/org.geppetto.frontend/blob/71af4037cb8dcf15ddc135bb17062aa9164925dd/src/main/webapp/js/GEPPETTO.Resources.js#L81) ExperimentStatusDescription and show that in the [tooltips](https://github.com/openworm/org.geppetto.frontend/blob/8c330abad290b78289f6168ab885f4a89cc2e0ff/src/main/webapp/js/GEPPETTO.FE.js#L224)
