### ISSUE TITLE
Add info on meaning of colours (yellow/orange/white) for connected elements to Quick Help info

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#458]
Would be good to have an explanation of the meaning of the colours when elements are selected in the Quick Help link on the top right. It is in docs here: http://docs.geppetto.org/en/latest/connections.html, but the Help button might be first place people would look...

Image on link above should suffice:

![](http://docs.geppetto.org/en/latest/_images/connection_colors.png)

**Comment by tarelli** [comment]
@LordKrabo will you create a new PR for this including also the less?
