### ISSUE TITLE
Add (verbose) tool tip on star button for persisting experiment

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#459]
Also tool tips on Run, Play etc. would be useful explaining difference between them, when they can be used etc.

**Comment by pgleeson** [comment]
There is not currently a tooltip on the persist star when the user is logged out, informing them that they have to log in to persist... Would be helpful for anyone just closing the tutorial widget

**Comment by tarelli** [comment]
Moved here https://github.com/OpenSourceBrain/geppetto-osb/issues/14
