### ISSUE TITLE
Installation instructions for 0.2.6

### ISSUE THREAD

**Issue by mschuene** [openworm/org.geppetto#472]
Hi, 
I installed version 0.2.6 of geppetto after the instructions from
http://docs.geppetto.org/en/latest/osxlinuxsetup.html
but ran in some issues.

I am running Kubuntu 15.04

1.) I have java 8 installed locally, which was not recognized by virgo-3.6.3 as 1.6+, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=440706 .
Installing virgo 3.6.4 solved this problem for me.
the link to the zip file in the setup instructions could be updated to virgo-3.6.4 if there are no problems with this version and geppetto that I am not aware of.

2.) I got an error when executing virgo startup.sh after deploying:
Unable to satisfy dependencies of bundle 'multi-artifact.plan-1-org.geppetto.frontend' at version '0.2.7': A library with the name 'org.springframework.spring' and a version within the range '[3.1.3.RELEASE, oo)' could not be found

The issue was that the update_server.py script only copies jar and war files to the virgo usr repository, but the frontend had an <Import-Library>org.springframework.spring;version="${spring.version}"</Import-Library> in it's pom.xml so that there is a org.springframework.spring-library-3.1.3.RELEASE.libd file in the target/classes/lib folder that was not copied.
The error was gone after I copied this file and so far everything seems to work.

I created a pull request to include the 'libd' extension in the update_server.py script
https://github.com/openworm/org.geppetto/pull/471

**Comment by LordKrabo** [comment]
@mschuene @tarelli I'm currently working on the documentation for installing 0.2.6 and 0.2.7 and updating it for Linux. I'm also running Linux Mint 17.3. Would you like me to include this in the documentation?

**Comment by mschuene** [comment]
@LordKrabo Yeah, would be great!

**Comment by tarelli** [comment]
@mschuene thanks, I just merged the PR!
