### ISSUE TITLE
Instance Type refactoring leftover improvements

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#475]
- [ ] cell added for network when converting to line viz from the API in some scenarios
- [x] Fix error while closing the project
- [ ] Change string into pointer for path parameters
- [ ] Refresh button for TV
- [ ] We are not throwing an exception when running a simulation and no feedback is provided to the user (See https://github.com/openworm/org.geppetto.simulation/blob/development/src/main/java/org/geppetto/simulation/manager/ExperimentRunThread.java#L319-L321)

**Comment by LordKrabo** [comment]
Add this to the new sprint @tarelli?

**Comment by tarelli** [comment]
We have created cards for the various improvements we want to do, closing this umbrella one.
