### ISSUE TITLE
Find an automated way of switching different versions of the ecore schema in XMIs

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#482]
Options:
- [x] Do it through travis on commit
- [ ] Do it through a maven plugin on mvn install
- [ ] Dot it through git smudge (Rob wouldn't recommend it)

**Comment by tarelli** [comment]
@LordKrabo I just added the encrypted tokens to all the repos so that travis can push things to a repo.
I would suggest you create a branch "test_automatic_push" for one of the repos, say org.geppetto.core, and try there the script that checks if there are paths to be changed in the XMIs and if so it changes them and then pushes the changes to the same branch
have a look at [this article](http://kevinyap.ca/2014/06/deploying-pelican-sites-using-travis-ci/).
I believe the script will endup being something like [this](https://github.com/iKevinY/iKevinY.github.io/blob/src/generate.sh#L59), let me know if you have any questions!

**Comment by tarelli** [comment]
@LordKrabo hey James, how's this going?

**Comment by LordKrabo** [comment]
Hi @tarelli did some work on the script but I haven't tested it yet. I'll start testing the script and see how it goes.

**Comment by LordKrabo** [comment]
@tarelli Managed to finally get this working.

**Comment by LordKrabo** [comment]
If you would like me to set this up on other repositories to test, I can create a pull request.
