### ISSUE TITLE
Insufficient access rights to create new experiment.

### ISSUE THREAD

**Issue by ondrejbalun** [openworm/org.geppetto#484]
Hello,

I always get "Insufficient access rights to create new experiment." error when creating a new Experiment. The geppetto runs on local machine with the sudo access rights.

Thanks for help!
ondrej

**Comment by tarelli** [comment]
@ondrejbalun you need to have the persistence bundle deployed, a running MySQL DB and a user with sufficient rights to create a new experiment and do other operations that require writing access. Depending on what your use cases for Geppetto are I can help you figure out what's the easiest way to achieve that. Which types of models are you interested to work with? Where do they come from?

**Comment by ondrejbalun** [comment]
Thank you for the swift answer. I would like to experiment on C. Elegans c302 model, present in the basic Greppetto installation.

**Comment by adrianq** [comment]
@ondrejbalun If you are interested only in the model itself, one option could be to use the project on OSB: http://opensourcebrain.org/projects/celegans If you are logged in with your OSB user you can create experiments, run simulations and so on. In this repo you have many different models apart from the one you mentioned.
However if you are interested in playing with the Geppetto code, you will have to deploy the persistence bundle, as @tarelli  said, and create a user group with privileged enough and a user. You can have a look [at this script about how to do something similar](https://github.com/openworm/org.geppetto.persistence/blob/master/src/main/java/org/geppetto/persistence/util/DBTestData.java) that can be found in the persistence bundle. [In here](http://docs.geppetto.org/en/latest/persistence.html) you can find some instruction about how to install the persistence bundle.

**Comment by pgleeson** [comment]
@ondrejbalun if you're interested in c302, I'd highly recommend getting the latest version of the code from https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302, installing the development version of jNeuroML and running c302 locally. The version on Geppetto is slightly older and not all of the simulation/replay of the different versions is yet well tested via Geppetto.

**Comment by tarelli** [comment]
@pgleeson not sure that's the best way to drive Open Source Brain's adoption. Geppetto doesn't have "old" models, there's just a sample on live which is a snapshot. OSB should be the place where to find the latest version and use them through Geppetto, whatever version is there, I'd highly recommend all models on OSB get tested so that people can use them along with all the tools we have built.

**Comment by ondrejbalun** [comment]
Thank you guys for helping! Actually, I tried the OSB and I could not simple work with it. It freezes a lot and I also could not find any more detailed documentation how to create experiment, run it, plot the data. There is only few lines on the Geppetto homepage.

**Comment by pgleeson** [comment]
@tarelli I was really referring to the copy of c302 bundled as a standard example in Geppetto (as the question was originally referring to). It's reasonably up to date, but there are many other updated versions of the network in the CElegansNeuroML repo. While these are accessible through OSB, some of the features (e.g. analog synapses) are quite new (last week or two) and the libraries to support these haven't been updated in the live OSB yet. Hence the local copy of c302 and the latest development jNeuroML are best to exploer c302.

@ondrejbalun the running of experiments via OSB is quite a new feature and documentation and ease of usability are still being worked on. It should work in most cases, but there are many things to polish and fully test. It's not in a state yet that we could suggest anyone should do any real work with it, it just shows what will be possible in the coming months.
