### ISSUE TITLE
Create skeleton output for validation

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/org.geppetto#487]
Greetings from the movement analysis team.  We have prepared an example JSON-format file for what we're hoping your simulation output can look like:

[ow_simulation_example.wcon](https://drive.google.com/file/d/0B9dU7zPD0s_LTGZDTmhuZFZxX1k/view?usp=sharing)

For complete information on the format we've selected, please visit:
https://github.com/openworm/tracker-commons/blob/master/WCON_format.md

If you want a program to generate this format for you, there are within that repository several engines in different languages available.  In the Python version, for instance, once your arrays are ready, you can call `.save_to_file` to create the WCON file.

Random notes:
- We're happy to start with whatever you can give us and then iterate from there.  Going forward, sharing an S3 bucket on the OpenWorm AWS account might be the best way to share a file
- For now, we just need a sample of "skeleton" coordinate articulation points for each frame of video.  Later the contour articulation points will be superior, and we'll calculate the skeleton from the contour ourselves.

**Comment by MichaelCurrie** [comment]
@gidili @tarelli can this become a priority for the Geppetto team?  This issue is the one that will close the loop and let the movement validation team validate the output of the simulation.  Thanks

**Comment by gidili** [comment]
@MichaelCurrie we will add to the agenda at the next geppetto meeting! If you we can discuss together 👍

**Comment by tarelli** [comment]
It's not a matter of priority @MichaelCurrie, if you have anyone who can volunteer happy to guide them. There are other cards (to get the latest of Sibernetic working again within Geppetto for instance) which are a prerequisite to this and have even higher priority OpenWorm wise that despite my efforts have not yet happened due to contributors working on it coming and going unfortunately.
