### ISSUE TITLE
Problems creating 2nd experiment in project

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#491]
There are a few issues with creating a 2nd experiment when one has been successfully run

- [x] It would be good if the dt and duration from the existing experiment could be copied by default  instead of being set to zero (minor) 
- [x] the field Simulator is blank, and typing it in (neuronSimulator) doesn't seem to save it. This is possibly the main reason I've not managed to run more than 1 experiment on a persisted proj.
- [x] There is still an issue (on live OSB) with setting the duration by typing in. In the console it reports: 

```
       ...setLength('2<br/>')
```
- [x] Deleting an experiment doesn't seem to work
- [x] When Run is pressed, there is no suggestion to record all v. Maybe copy all watched variables from first experiment?
- [x] When there is a failure to run (for whatever reason) the Run button is still disabled
- [x] When new experiment added, make this active by default (or ask to switch to it)

**Comment by tarelli** [comment]
Good list! Some might be bugs, others useful enhancements.

**Comment by slarson** [comment]
Having trouble reproducing the `setLength('2<br/>')` -- tested on OSB with Chrome and Firefox.  @pgleeson can you say more about where this is happening (Platform, Browser type, Browser version, which model you see this happening on?)

**Comment by slarson** [comment]
Same question for 

>the field Simulator is blank, and typing it in (neuronSimulator) doesn't seem to save it

Can't reproduce ATM.

**Comment by tarelli** [comment]
@slarson reproduced on both Chrome and Firefox on OSX (but saw it happening also on Windows at the lab). With a persisted project on OSB, clicked new experiment, typed neuron (or whatever) in the simulator box, pressed enter, the following appears 
![screen shot 2016-06-20 at 12 15 44](https://cloud.githubusercontent.com/assets/81127/16192367/c2a0d52c-36e0-11e6-8569-ec86824c78af.png)
in the console
```
Project.getExperimentById(117).simulatorConfigurations['Golgi(network_Soma)'].setSimulator('neuron<br>')```
![screen shot 2016-06-20 at 12 00 09](https://cloud.githubusercontent.com/assets/81127/16192002/e41fc070-36de-11e6-9544-fa05cf936cac.png)
For the second one "the field simulator is blank" that will be covered when the new experiment will take the value for all the fields from a pre-existing experiment. I couldn't reproduce the part about "not saving it" either, see dashboard where, although with "<br>" the new value is there:
![screen shot 2016-06-20 at 12 18 04](https://cloud.githubusercontent.com/assets/81127/16192426/2585d8b8-36e1-11e6-81d9-e3f836e75a0a.png)
