### ISSUE TITLE
Create a virtual machine image that can be used to create a Geppetto development environment

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#493]
- [x] Create an image (docker?) with the sources of Geppetto, the Virgo server and the Eclipse Luna (or Mars if you can get everything to work) environment (including the Virgo tooling plugin). The environment would work out of the box and Geppetto would start successfully without need to tweak or do anything.
- [ ] Add documentation to docs.geppetto.org for how to launch the image

**Comment by LordKrabo** [comment]
Would Digital Ocean be an option for hosting?

**Comment by tarelli** [comment]
@petepy @slarson this is the card

**Comment by LordKrabo** [comment]
Adding to sprint 75

**Comment by LordKrabo** [comment]
Adding to sprint 76.

**Comment by tarelli** [comment]
@LordKrabo we need somebody to commit to do it within a given sprint to set the milestone
