### ISSUE TITLE
Generate a downloadable figure from the content of any widget and/or 3D canvas

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#495]
It would be useful for scientists to be able to selectively turn the content of the screen in one or multiple figure, scenarios:
- [ ] One figure for a specific widget
- [ ] One figure for every widget
- [ ] One figure just for the 3D canvas
- [ ] One figure for the canvas plus every widget
- [ ] Allow the user to give a name and a caption to each of the figures

**Comment by tarelli** [comment]
http://phantomjs.org/screen-capture.html This could be maybe used

**Comment by LordKrabo** [comment]
@tarelli Add to sprint 74 or 75?

**Comment by tarelli** [comment]
This was done for the plotting widget
