### ISSUE TITLE
Improve setup.py script

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#497]
Add a command line interface to the script to guide the user to specify which bundles they want to install which will also update config.json and geppetto.plan.
- [x] Core bundles (always installed)
  "org.geppetto.model"
  "org.geppetto.core"
  "org.geppetto.simulation",
  "org.geppetto.frontend"
- [x] Optional bundles, all the other ones, we ask a question for each one of them.
- [x] We update [config.json](https://github.com/openworm/org.geppetto/blob/development/utilities/source_setup/config.json)
- [x] We update [pom.xml](https://github.com/openworm/org.geppetto/blob/development/pom.xml)
- [x] We update [geppetto.plan](https://github.com/openworm/org.geppetto/blob/development/geppetto.plan)
- [x] If the selected bundles do not exist (at the same level of org.geppetto) we also clone them at the end (the url comes from the config.json) otherwise we just update the various files
- [x] Create a PR

Additional modification - have an "interactive" and a "non-interactive" mode. The non-interactive mode will just include the default scripts.

**Comment by LordKrabo** [comment]
Haven't done anything on this yet, will work on this for sprint 75.

**Comment by LordKrabo** [comment]
I have a setup_optional script - this allows the user to select the repos I need. Having said that, I am not sure whether I should merge this with @slarson 's setup script or whether the two should be kept separate.
