### ISSUE TITLE
Add a servlet to generate a Geppetto project to load supported formats

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#499]
Similarly to load_project _from_url the servlet load_file could generate a Geppetto project and a geppetto model to load a supported model inside geppetto.
This could be used to load an NWB file, an OBJ, a Collada, a NeuroML, etc. The user wouldn't have to worry about creating a project or anything, they'd just point the servlet to their external file. This would enable to use Geppetto as a simple viewer. 

The project generated can be different for the different types. For instance for an NWB file we want to show by default an opened control panel filtered by all the sweeps. For an OBJ or a Collada file we want to show the 3D model centered in the scene, etc. We should probably have a template for each supported format and such template should probably live inside the model bundle of that format along with a service to retrieve it.

Optionally: We could add in the dashboard a special project where you can drag and drop a file which then gets uploaded and visualized.

- [ ] Extend ServiceRegistry to receive a parameter when registerModelFormat is called. The parameter is the extension, so instead of just saying registerModelFormat("COLLADA") we'd do registerModelFormat("COLLADA","dae")
- [ ] Add GenerateGeppettoArtifacts class (use [this](https://github.com/openworm/org.geppetto.frontend/blob/04629f881ade99f3dcfd326bfebcb09d2ed560d5/src/main/java/org/geppetto/frontend/dashboard/service/GeppettoProjectsController.java) as template) which will reply to the three generate calls. The implementation of the three of them will just use methods defined in the GeppettoManager (see below) which returns a String.
- [ ] Extend GeppettoManager to handle the new generate* calls. The extension will be checked, the services registry will be queried, the specialised template will be used if the model interpreter returned by the registry supports the generate* feature, otherwise it will fall back to the default template. The Geppetto manager method will return a String.
- [ ] Add generateProject?model=fileURL servlet
- [ ] Add generateGeppettoModel?model=fileURL servlet
- [ ] Add generateScript?model=fileURL servlet
- [ ] Create feature generateProjectFeature optional for model interpreters
- [ ] Create feature generateGeppettoModelFeature optional for model interpreters
- [ ] Create feature generateScriptFeature optional for model interpreters
- [ ] Create default template for GeppettoProject (use [velocity](https://github.com/openworm/org.geppetto.core/blob/17ac0b5367a2c6ad8cd549c82b97270dad7a9fd6/src/test/java/org/geppetto/core/VelocityUtilsTest.java))
- [ ] Create default template for GeppettoModel (use [velocity](https://github.com/openworm/org.geppetto.core/blob/17ac0b5367a2c6ad8cd549c82b97270dad7a9fd6/src/test/java/org/geppetto/core/VelocityUtilsTest.java))
- [ ] Create default template for GeppettoScript (use [velocity](https://github.com/openworm/org.geppetto.core/blob/17ac0b5367a2c6ad8cd549c82b97270dad7a9fd6/src/test/java/org/geppetto/core/VelocityUtilsTest.java))
- [ ] Create NWB template for GeppettoProject (use [velocity](https://github.com/openworm/org.geppetto.core/blob/17ac0b5367a2c6ad8cd549c82b97270dad7a9fd6/src/test/java/org/geppetto/core/VelocityUtilsTest.java))
- [ ] Create NWB template for GeppettoModel (use [velocity](https://github.com/openworm/org.geppetto.core/blob/17ac0b5367a2c6ad8cd549c82b97270dad7a9fd6/src/test/java/org/geppetto/core/VelocityUtilsTest.java))
- [ ] Create NWB template for GeppettoScript (use [velocity](https://github.com/openworm/org.geppetto.core/blob/17ac0b5367a2c6ad8cd549c82b97270dad7a9fd6/src/test/java/org/geppetto/core/VelocityUtilsTest.java))

Bonus task

The above to be used will require going to such URL;
```
http://live.geppetto.org/load_project_from_url?url=http://live.geppetto.org/generate_project?model=http://dropbox/myColladaModel.dae
```
The above URL could be generated through a UI:

- [ ] Add to the dashboard a javascript API command that when invoked will make a special project appear. This project supports drag and drop of a file. This will require an additional servlet to upload the file and return a URL to it.

Design

 ![Image](https://www.lucidchart.com/publicSegments/view/6a714d37-f382-4b60-81eb-373a3ebbfbfe/image.png)

**Comment by LordKrabo** [comment]
Added to sprint 75

**Comment by LordKrabo** [comment]
Now added to sprint 77 @tarelli @niteshthali08
