### ISSUE TITLE
Preview graphics

### ISSUE THREAD

**Issue by rgerkin** [openworm/org.geppetto#502]
@tarelli @niteshthali08 When selecting either an NWB experiment, or a sweep from that experiment, it would be helpful to have preview graphics (e.g. thumbnails) to help guide the user to select the one that they want.  At least for the NWB files from the Allen Institute, there are some very small preview graphics generated from their NWB files that we could probable use.  For example, [this](http://celltypes.brain-map.org/mouse/thumbnail/ephys_trace?id=487601493) is a preview of the long-square sweeps from the experiment with ID 487601493.  It is only about 8K, and the URL is easy to parse and stable.  

There are also other small graphics, including morphology previews, as you can see in [their interface](http://celltypes.brain-map.org/mouse/experiment/electrophysiology/487601493?mode-toggle.x=20&mode-toggle.y=37&mode-toggle=morphology).

**Comment by LordKrabo** [comment]
Adding this one to sprint 74 @tarelli @rgerkin

**Comment by LordKrabo** [comment]
Sorry @tarelli moving 77.

**Comment by tarelli** [comment]
For Nitesh, tasks breakdown: 

- [ ] Understand how to get a URL from Allen for every sweep, e.g. http://celltypes.brain-map.org/mouse/thumbnail/ephys_trace?id=487601493
- [ ] Add a preview variable of type ImageType to the Sweep or to the Signal type (depending on what preview images are available) and populate the value with the Allen URLs, see [this](https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/blob/master/src/main/java/uk/ac/vfb/geppetto/AddImportTypesImageQueryProcessor.java#L98) for a sample.
- [ ] Extend configuration of the control panel in the sample to add an image in its configuration, see [this](https://github.com/VirtualFlyBrain/geppetto-vfb/blob/master/ComponentsInitialization.js) for a sample.
- [ ] Test correct preview images are displayed in the control panel
- [ ] Extend unit test to check images are added

**Comment by niteshthali08** [comment]
@tarelli : The preview image is available at experiment level i.e. One preview image/NWB file. I couldn't get URL for preview image at sweep level. I have added this experiment level preview image to the list of Metadata which we display on landing page.

**Comment by tarelli** [comment]
@niteshthali08 is there a PR for this?
