### ISSUE TITLE
NWB Sweep Preview interface

### ISSUE THREAD

**Issue by rgerkin** [openworm/org.geppetto#503]
What will the interface for choosing specific sweeps from an NWB file look like?  [Here](http://celltypes.brain-map.org/mouse/experiment/electrophysiology/487601493?mode-toggle.x=20&mode-toggle.y=37&mode-toggle=morphology) is what it looks like on the Allen site.  The different stimulus types are presented in a drop-down menu, and then once a stimulus type is selected, it shows all of the stimuli of that type (usually <20), and then the user can select one of those and hide (gray out) the others.  There is no guarantee that all future NWB files from other labs will be easily organized by stimulus type, but it is the most intuitive way (for me, as an electrophysiologist) to view them.  

When #500 is finished, it seems like it would be possible to lazily load ~10 sweeps like this, or possibly to load and quickly downsample selected sweeps for a preview.  Certainly any sort of preview of the data before it is loaded into a widget doesn't need to hit the UI at the full sampling rate.

**Comment by LordKrabo** [comment]
@rgerkin Can I add this to sprint 74?

**Comment by LordKrabo** [comment]
Okay have just spoken to @tarelli will move this to Sprint 77.
