### ISSUE TITLE
Add ability to lazy load a value backend

### ISSUE THREAD

**Issue by LordKrabo** [openworm/org.geppetto#504]
@niteshthali08 I am adding these to Sprint 75.

- [x] Create branch 'importValue' for every bundle that needs one
- [x] Add ImportValue to Geppetto ecore (in org.geppetto.model) 
- [x] Add backend functionality to resolve a ImportValue

**Comment by niteshthali08** [comment]
@tarelli : Could you please list set of actions which will invoke importType functionality ?

**Comment by tarelli** [comment]
@niteshthali08 at the moment it's just from the Javascript API, when you have an ImportType you can call resolve on it, see [this](https://github.com/openworm/org.geppetto.frontend/blob/b7945384e419b581872d40db9279be27323f2cbc/src/main/webapp/js/model/ImportType.js#L100)

**Comment by niteshthali08** [comment]
@tarelli : What would be the value of "String path" received by function "resolveImportValue(String path)" would look like ?

**Comment by tarelli** [comment]
@niteshthali08 the path of the variable or type that the value is attached to (e.g. nwbSample.response currently or a more complex one given the new design nwbSample.sweep100.stimulus.response.recording)

**Comment by niteshthali08** [comment]
Thanks @tarelli, I need your help in understanding few things. Can we have a small meeting on Thursday or Friday ?

**Comment by tarelli** [comment]
Hey Nitesh, I'm out of commission for the rest of the week but @gidili can
answer those questions as I've caught him up with what you are doing.

**Comment by niteshthali08** [comment]
@gidili: are you available for some time during this week for a small meeting ?

**Comment by gidili** [comment]
@niteshthali08 yes! I'll send you an email to schedule

**Comment by LordKrabo** [comment]
Add this to sprint 76 @niteshthali08 @tarelli @gidili ?

**Comment by niteshthali08** [comment]
@tarelli: I have committed the code. So I wanted to write a jUnit test case to call the functions on backend so that I can test them as they are executed. I just copy pasted code from one of the existing test case DataSourcesGeppettoManagerTest.java into ImportValueTest. I have created test2 folder inside resources with NWB stuff.  Could you please help me in getting this work ? I want this test case to call the method resolveImportValue(path).

**Comment by tarelli** [comment]
@niteshthali08 I haven't found your test anywhere but I committed some code to show you some more pointers

**Comment by niteshthali08** [comment]
@tarelli : Sorry for that there was a merge conflict while pushing which got neglected by me.

**Comment by niteshthali08** [comment]
@tarelli : I have modified nwbModelInterpreter to return display text according to the [proposed design for lazy loading](https://www.lucidchart.com/documents/edit/19d75b64-d479-48bc-8b0b-a6303e5ea49e#). It would be great if we can have one small meeting at the earliest in coming week to get some pointers on implementing frontend.

**Comment by niteshthali08** [comment]
I tried to write a test case to test out the resolveImportValue functionality. I created "ImportValueTest.java" but it is throwing an exception at the line given below. "appContext" is returned as null.
`public static Object getNewServiceInstance(String discoveryId) throws GeppettoInitializationException
	{
	ApplicationContext appContext = ApplicationListenerBean.getApplicationContext(discoveryId);`
      ...
}
