### ISSUE TITLE
Displaying multiple SWC files in geppetto

### ISSUE THREAD

**Issue by AdamRTomkins** [openworm/org.geppetto#510]
I am trying to visualize two swc files simultaneously using geppetto. I am attempting to modify the Ganglion Cell from EyeWire example.

I am not sure on the format to include multiple swc files (15 and 56 in the zip file).

[test.zip](https://github.com/openworm/org.geppetto/files/325642/test.zip)

**Comment by tarelli** [comment]
Hi @AdamRTomkins, can you try with the code below? You need to create two variables if you want to instantiate both SWCs. In the lines below you are adding types (as if you were defining your own classes), one for each SWC, in the variables entry you are saying "I want to instantiate them".

```
<?xml version="1.0" encoding="ASCII"?>
<gep:GeppettoModel
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:gep="https://raw.githubusercontent.com/openworm/org.geppetto.model/master/src/main/resources/geppettoModel.ecore"
    xmlns:gep_1="https://raw.githubusercontent.com/openworm/org.geppetto.model/master/src/main/resources/geppettoModel.ecore#//types">
  <variables
      id="AutoGeneratedSWC56"
      name="AutoGenerated 56"
      types="//@libraries.0/@types.0"/>
  <variables
      id="AutoGeneratedSWC15"
      name="AutoGenerated 15"
      types="//@libraries.0/@types.1"/>
  <libraries
      id="swc"
      name="na">
    <types xsi:type="gep_1:ImportType"
        id="One"
        url="SERVER_ROOT/app_data/test/56.swc"
        modelInterpreterId="swcModelInterpreter"/>
    </libraries>
    <types xsi:type="gep_1:ImportType"
        id="One"
        url="SERVER_ROOT/app_data/test/15.swc"
        modelInterpreterId="swcModelInterpreter"/>
    </libraries>
</gep:GeppettoModel>

```

**Comment by AdamRTomkins** [comment]
Thank you @tarelli 
For posterity, there was one further error in the code, with a duplication of  the </libraries> tag, and the first must be removed.
