### ISSUE TITLE
Active icon for new experiments not being updated

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#515]
Have tried the cloning/new experiment functionality on latest development branches and works a lot better, but it seems the icon indicating which experiment is active is not being updated:

![selection_854](https://cloud.githubusercontent.com/assets/1556687/17257931/649f069c-55bc-11e6-84e5-1493de6ad95f.jpg)

In this project Experiment 3 was actually active (it ran when Run was pressed) but the ticks (bottom right) for previous experiments were still shown.

Also, should it be possible to switch between active experiment at this screen?

**Comment by tarelli** [comment]
@pgleeson there is no icon to indicate which experiment is active, the active experiment has just a darker background (see New Experiment 3 above). The icon on Thalamocortical - net (the tick) is to activate that experiment instead (which should answer your other question). Makes sense?

**Comment by pgleeson** [comment]
Ok, understood. What got me was the tooltip on the tick: "Active Icon"; I assumed this meant "This experiment is active".

Maybe change text to: "Activate this experiment"

**Comment by tarelli** [comment]
Yup, makes sense!

**Comment by tarelli** [comment]
Done https://github.com/openworm/org.geppetto.frontend/commit/6cfff7c05526fc69935ba5df805502577ef59ea8
