### ISSUE TITLE
Double display of cells when changing geometry type

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#519]
Before (on http://comodl.org/projects/thalamocortical?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FThalamocortical%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FLayer23_NoConns.net.nml):

![selection_008](https://cloud.githubusercontent.com/assets/1556687/17926907/3e72c31c-69eb-11e6-9457-972677c3c6c8.jpg)

After running: Layer23_NoConns.setGeometryType('cylinders')

![selection_007](https://cloud.githubusercontent.com/assets/1556687/17926950/66a85054-69eb-11e6-8d81-060a9e0887b6.jpg)

i.e. all cells are shown again at (0,0,0) above existing net. Has been a problem for some time.

**Comment by pgleeson** [comment]
Still an issue in live version...

**Comment by pgleeson** [comment]
Seems to be fixed now in development/comodl. However the cells lose their colour:

![selection_290](https://user-images.githubusercontent.com/1556687/27078956-be69cf9c-502d-11e7-9d3e-4d92c890eb25.png)

![selection_289](https://user-images.githubusercontent.com/1556687/27078970-c6c2b97e-502d-11e7-9ed3-a3777687ef6a.png)

**Comment by tarelli** [comment]
@jrmartin can we add a test in the casper Core suite to check that acnet2 doesn't loose the colour when switching to lines and then back to cylinders acnet2.setGeometryType("lines") acnet2.setGeometryType("cylinders")?

**Comment by mattearnshaw** [comment]
fix for loss of colours was merged
