### ISSUE TITLE
Status circle not getting updated on submission or successful run of experiment

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#520]
No change in orange circle during exp run.

![selection_009](https://cloud.githubusercontent.com/assets/1556687/17928597/636d1aac-69f3-11e6-8e81-49215d86f4bc.jpg)

http://comodl.org/projects/acnet2?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FACnet2%252Fmaster%252FneuroConstruct%252FgeneratedNeuroML2%252FTwoCell.net.nml#

**Comment by gidili** [comment]
@pgleeson any javascript console errors after the green dot updates on the dashboard but not on the experiments table? Can't test it now but that would help narrow it down

**Comment by slarson** [comment]
Fixes for this are in progress

**Comment by pgleeson** [comment]
Thanks @slarson!
