### ISSUE TITLE
Upload to dropbox through GUI

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#523]
Is it currently possible to link to user's dropbox account for auto upload of results through GUI interaction alone?

**Comment by pgleeson** [comment]
@tarelli any update on this?

**Comment by mattearnshaw** [comment]
haven't been able to get this to work manually, authentication works but no files appear.

**Comment by tarelli** [comment]
@mattearnshaw do you get any error? We have the QUnit persistence tests that test the dropbox upload, can you try run those (you'll first have to do the linking for your user for them to pass)

**Comment by mattearnshaw** [comment]
@tarelli the unit test works. no error before, but since it's working in some capacity, i will take another look tomorrow

**Comment by pgleeson** [comment]
Needs to be brought back to life...

**Comment by pgleeson** [comment]
Infor on this should be added to this page in OSB docs: https://github.com/OpenSourceBrain/OSB_Documentation/blob/master/contents/Help/12_Running_Simulations_on_OSB.md

**Comment by mattearnshaw** [comment]
gui linking/upload working on comodl with documentation in progress...

relevant PRs to be merged before closing
https://github.com/OpenSourceBrain/geppetto-osb/pull/84
https://github.com/openworm/org.geppetto.core/pull/141
https://github.com/openworm/org.geppetto.simulation/pull/134
https://github.com/openworm/org.geppetto.frontend/pull/722
