### ISSUE TITLE
More helpful warning messages

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#525]
I'd like to make these warnings more informative:

![selection_015](https://cloud.githubusercontent.com/assets/1556687/18271274/317eccc6-7429-11e6-9f8a-b98cdc86d833.jpg)

Obviously this is a general Geppetto error, not OSB specific, but is it ok to add a sentence: Please try signing in if you would like to persist projects.

**Comment by tarelli** [comment]
@pgleeson FYI These errors won't be there once I'll be done merging the pending branches since the action won't be possible to begin with unless the user is signed in.

**Comment by pgleeson** [comment]
Good to know. I'll wait then...
