### ISSUE TITLE
"View NeuroML source file" does not work for OSB Samples 

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#528]
e.g. for ACnet, press Model Description, and the View NML2 link points to: file:///home/virgo/geppetto/OSB_Samples/AuditoryCortex/MediumNet.net.nml. Would it be better to point this to https://raw.githubusercontent.com/OpenSourceBrain/OSB_Samples/master/AuditoryCortex/MediumNet.net.nml? All other js/json/xmi are treated as local files

**Comment by pgleeson** [comment]
@tarelli sorry for filling up https://github.com/openworm/org.geppetto/issues with OSB/NML specific issues...

**Comment by tarelli** [comment]
@pgleeson No worries,  also when it's a bug of the geppetto NeuroML bundle it can be logged directly in that repo

**Comment by pgleeson** [comment]
Fixed with commit above

**Comment by adrianq** [comment]
@pgleeson @tarelli I deployed yesterday OSB_Samples, Geppetto and OSB(redmine) and all of them are using the development branch. Just to let you know @pgleeson  as your last commit is pointing to master for the OSB_Samples..

**Comment by pgleeson** [comment]
@adrianq, I've made a few changes today on dev branch of  OSB_Samples, and testing on comodl,which will eventually be merged to master. There will be a difference between dev & master here always as the dev branch has to use the URLs with development and master uses master.
