### ISSUE TITLE
Home button on OSB projects...

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#533]
When clicked, home button on right of OSB 3D view beside Persist button:

![selection_119](https://cloud.githubusercontent.com/assets/1556687/19350165/977b1a10-914e-11e6-8eb8-ef99017fad3f.png)

goes to this: 

![selection_121](https://cloud.githubusercontent.com/assets/1556687/19350297/0eb7f120-914f-11e6-900b-ef779c762ee9.png)

Maybe go to "Your models" tab if logged in, else go to OSB project main page? Or remove?

@tarelli What's your preferred repo for issues like this for Geppetto related OSB issues?

**Comment by tarelli** [comment]
@pgleeson the [geppetto-osb extension repo](https://github.com/opensourcebrain/geppetto-osb) since that's the one responsible of OSB business logic. Thx!
