### ISSUE TITLE
Add confirm dialog to Delete experiment button

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#538]
![selection_126](https://cloud.githubusercontent.com/assets/1556687/19524357/598edc98-9615-11e6-822a-7a1623737df1.png)

It's quite easy to accidentally click the cross for deleting an experiment when expanding exp info or switching between experiments...

**Comment by pgleeson** [comment]
One for @mattearnshaw...

**Comment by mattearnshaw** [comment]
fixed in https://github.com/mattearnshaw/org.geppetto.frontend/commit/5ee50090c641b5c66de58b67cdb7f705c6f56e9f

**Comment by tarelli** [comment]
@mattearnshaw Create a PR to development when you'd like this to be reviewed! As for undo, we'd have to migrate the Project model first to use EMF which supports transactions, undo, etc. It's something I'd like to do at some point but not the smallest of tasks...

**Comment by tarelli** [comment]
Created a card to track the migration of Projects and Experiments to EMF https://github.com/openworm/org.geppetto/issues/541
