### ISSUE TITLE
production build with master profile causing errors

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto#558]
I'm getting errors with ```mvn clean install -P master "-DcontextPath=org.geppetto.frontend"``` 
see https://geppetto-dev1.virtualflybrain.org/org.geppetto.frontend/geppetto?load_project_from_url=http://v2a.virtualflybrain.org/conf/vfb.json
that I do not get with ```mvn clean install -P development "-DcontextPath=org.geppetto.frontend"```
see https://geppetto-dev.virtualflybrain.org/org.geppetto.frontend/geppetto?load_project_from_url=http://v2a.virtualflybrain.org/conf/vfb.json

main one seems to be:

```
Uncaught Error: Cannot find module "eval"
    at main.bundle.js:1
    at Object.<anonymous> (main.bundle.js:1)
    at e (main.bundle.js:1)
    at main.bundle.js:1
    at main.bundle.js:1
```

**Comment by tarelli** [comment]
@Robbie1977 that was how @adrianq and I spent Easter Monday :) If you merge from the latest of development or master it will be fixed!
