### ISSUE TITLE
Context Path is not being read from GeppettoConfiguration at least for the pom.xml

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto#571]
For future reference: https://stackoverflow.com/questions/849389/how-to-read-an-external-properties-file-in-maven

**Comment by adrianq** [comment]
It seems to be an error with the cross origin that may have to do with the mvn install for production as well:
-  Review-> https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/WEB-INF/web.ejs#L91
- Example: http://www.opensourcebrain.org/projects/hodgkin-huxley-tutorial?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fopenworm%2Fhodgkin_huxley_tutorial%2Fmaster%2FTutorial%2FSource%2FHHCellNetwork.net.nml  No cross origin error without www

**Comment by tarelli** [comment]
Still needs fixing

**Comment by tarelli** [comment]
This is still a problem

**Comment by tarelli** [comment]
This happens also when specifying for instance the useSsl paramter maven side. The parameter is correctly read from Webpack and it is used by the Webpack build. However the configuration file is not updated and therefore when the application will load useSsl would still have the value hardcoded in the file that is not necessarily the one that was passed via Maven. A solution for this would be to update the webpack code to overwrite the GeppettoConfiguration.json file with the values coming from Maven. @adrianq thoughts?
