### ISSUE TITLE
No 3d view - ACNet2 example

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto#573]
Loading [ACnet2 from live](https://live.geppetto.org/geppetto?load_project_from_id=5) (incognito window - no cache) results in

<img width="1440" alt="screen shot 2017-08-18 at 13 34 48" src="https://user-images.githubusercontent.com/3452783/29468359-47a6a486-841a-11e7-9834-68fe1e52bf45.png">

ie
 - no 3d canvas / entities aren't  displayed 
-  the legend for the conn matrix seems broken

**Comment by borismarin** [comment]
A similar problem seems to occur on the [OSB deployment](http://opensourcebrain.org/projects/acnet2/models?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FACnet2%2Fmaster%2FosbSessions%2Fsample%2FSample_Session.json)

<img width="1440" alt="screen shot 2017-08-18 at 13 42 53" src="https://user-images.githubusercontent.com/3452783/29468604-56be376c-841b-11e7-9f54-49882259c9db.png">

**Comment by mattearnshaw** [comment]
note to self: `Canvas.display` getting no instances …

**Comment by tarelli** [comment]
@mattearnshaw we fixed this right? @borismarin does it still happen?

**Comment by mattearnshaw** [comment]
I thought it was still broken (although we fixed something related) but not able to replicate now

**Comment by borismarin** [comment]
Seems to be working now:
<img width="1440" alt="screen shot 2017-12-05 at 13 53 40" src="https://user-images.githubusercontent.com/3452783/33616356-d3ca529c-d9c3-11e7-9ccf-eeb015671c35.png">

**Comment by borismarin** [comment]
@mattearnshaw @tarelli  closed, but would be good to know what was broken.

**Comment by tarelli** [comment]
From what I remember it was timing when restoring a view and the canvas wasn't there yet, something along those lines.
