### ISSUE TITLE
Having trouble deploying Geppetto

### ISSUE THREAD

**Issue by vamsi1994** [openworm/org.geppetto#577]
When I try to open Geppetto, it's just showing a blank page. I'm on windows 10.
I followed these instructions: [http://docs.geppetto.org/en/latest/windowssetup.html](http://docs.geppetto.org/en/latest/windowssetup.html)
I did everything except changing the value of _sourcesdir_ field and setting the M2 environment variable.
Using Java 1.8.0_144 - 64bit
Trace from Virgo after running startup.bat: [https://pastebin.com/RiPGh8cc](https://pastebin.com/RiPGh8cc)

**Comment by tarelli** [comment]
@vamsi1994 Hi, the log from Virgo doesn't have any error, what URL are you pointing your browser to? Can you put a screenshot? Thanks!

**Comment by vamsi1994** [comment]
@tarelli URL: [http://localhost:8080/org.geppetto.frontend](http://localhost:8080/org.geppetto.frontend)
![screenshot 3](https://user-images.githubusercontent.com/6739759/31705966-ebbb271c-b404-11e7-8f04-cd72923e1b5d.png)

**Comment by tarelli** [comment]
That's weird, can you check the browser debug console see if you have any Javascript errors?

**Comment by vamsi1994** [comment]
@tarelli Console log raw: [https://pastebin.com/raw/EmhW1C1T](https://pastebin.com/raw/EmhW1C1T)

![console log](https://user-images.githubusercontent.com/6739759/31712972-53536942-b41a-11e7-9967-d35a5d5ba58c.PNG)

**Comment by tarelli** [comment]
Alright we have an error at least! Can you please paste the full output of mvn install on org.geppetto.frontend? Thanks!

**Comment by vamsi1994** [comment]
Follow this link: [https://github.com/openworm/org.geppetto.frontend/issues/693](https://github.com/openworm/org.geppetto.frontend/issues/693)
