### ISSUE TITLE
NeuroML editor and ability to easily simulate custom NeuroML files

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#59]
A Geppetto widget with the ability of creating/modifying NeuroML files

**Comment by JustasB** [comment]
I second this idea. My current work cycle is to edit NML file locally, validate with jnml, make an SVG as a quick check, then check into OSB-linked github repo, then refresh gepetto. Going from editing nml to refresh gepetto would be a time saver.

**Comment by pgleeson** [comment]
An alternative is to install a copy of Geppetto locally and load/view local NML files...
