### ISSUE TITLE
How to cite geppetto?

### ISSUE THREAD

**Issue by orena1** [openworm/org.geppetto#591]
Thanks.

**Comment by tarelli** [comment]
@orena1 we have a paper currently under review. In the next few weeks it will go live as a preprint.Do you need to cite earlier than that?

**Comment by orena1** [comment]
No problem, it can wait.

**Comment by orena1** [comment]
Any update on this one?

**Comment by orena1** [comment]
Found it:
https://royalsocietypublishing.org/doi/10.1098/rstb.2017.0380

Might be good to add it to the README

**Comment by gidili** [comment]
@orena1 Yes! 

Here it is: https://royalsocietypublishing.org/doi/10.1098/rstb.2017.0380

Now we can close this for real 🙆‍♂️
