### ISSUE TITLE
Split dependencies between geppetto core and geppetto applications

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#603]

**Comment by tarelli** [comment]
@dariodippi @rodriguez-facundo @filippometacell assigned you all to this. Facu will own the coding side of things.

**Comment by tarelli** [comment]
@dariodippi when you got a chance can you update with the outcome of the meeting?

**Comment by rodriguez-facundo** [comment]
This has been done [here](https://github.com/openworm/geppetto-client/commits/remove-packages) in particular check [1️⃣](https://github.com/openworm/geppetto-client/commit/7c0717e5a6a29c757b377dce6cd36efdfa3c1bd7) and [2️⃣](https://github.com/openworm/geppetto-client/commit/41e8180bbb0ff00039bb089dc1c9d0fd94384355) 
We are saying good-bye to:
```
"aws-sdk": "^2.108.0",
"image-webpack-loader": "^2.0.0",
"jquery.cookie": "^1.4.1",
"jsx": "^0.9.89",
"lg-autoplay": "^1.0.4",
"lg-zoom": "^1.1.0",
"lodash.clone": "^4.5.0",
"react-at-rest": "2.0.11",
"react-autosuggest": "^9.3.2",
"react-collapsible": "^2.3.1",
"react-drag-and-drop": "2.4.0",
"react-router": "^4.1.1",
"react-router-dom": "^4.1.1",
"react-simpletabs": "0.7.0",
"react-tap-event-plugin": "^2.0.1",
"three-loaders-collada": "^1.0.1",
```
