### ISSUE TITLE
geppetto dockerfile might be split at line 55

### ISSUE THREAD

**Issue by rodriguez-facundo** [openworm/org.geppetto#608]
The Dockerfile to build Geppetto contains 2 steps. The first one where required packages to build Geppetto are installed and the second one where Geppetto repos are cloned and installed. 

We could take those 2 steps and put them in different docker images, so we avoid repeating the first step. We might also consider using fewer layers to avoid container size growth.

**Comment by tarelli** [comment]
@rodriguez-facundo in progress?

**Comment by rodriguez-facundo** [comment]
I will pull java-virgo-maven:latest from dockerhub to test it locally before updating this card.

**Comment by rodriguez-facundo** [comment]
This has been done [here](https://github.com/MetaCell/java-virgo-maven) and is ready for review
