### ISSUE TITLE
Implement properly semantic versioning

### ISSUE THREAD

**Issue by ddelpiano** [openworm/org.geppetto#615]
Understand the different rules on the different types of codebases to decide when we have a minor or a major release of a given project.

**Comment by filippomc** [comment]
Drafting here: https://docs.google.com/document/d/11MvhtGcE34Sc_9F8f7Uwtp-f2QkUarPSmae_gD4JdDo/edit#

**Comment by filippomc** [comment]
@ddelpiano @tarelli @gidili I'm finished with what I think it's an acceptable draft. Waiting for your feedback.
