### ISSUE TITLE
Houston, we have a problem...Error opening Project

### ISSUE THREAD

**Issue by rishistyping** [openworm/org.geppetto#630]
@ http://www.opensourcebrain.org/projects/c302?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252Fc302%252Fmaster%252Fexamples%252Fparametersweep%252FIClamp_GenericNeuronCell.net.nml

![Screenshot_2020-03-22 Overview - c302 - Open Source Brain](https://user-images.githubusercontent.com/55334249/77244716-7e3e3680-6c3e-11ea-8561-588bace187dd.png)

**Comment by pgleeson** [comment]
Sorry for the delay getting back to you about this @EXYNOS-999. As you may have seen, recent updates to c302 mean that this model now loads successfully. However, the code in https://github.com/openworm/c302/tree/master/examples/parametersweep is experimental and subject to change. 

The core examples generated from c302 (as summarised in the matrix here: https://github.com/openworm/c302/blob/master/examples/summary/README.md) should still work fine.

**Comment by rishistyping** [comment]
Thanks @pgleeson. Apprecite it!
