### ISSUE TITLE
Live Demo is down

### ISSUE THREAD

**Issue by ghost** [openworm/org.geppetto#634]
Just wanted to report that the live demo is down:

https://live.geppetto.org/

504 Gateway Time-out
nginx/1.15.6

**Comment by clausagerskov** [comment]
still down so not sure why the issue is closed

**Comment by pgleeson** [comment]
@tarelli @filippomc Is it still the intention to host a live version of geppetto at the above address?

**Comment by tarelli** [comment]
@pgleeson we are building a new showcase that will replace live.geppetto
