### ISSUE TITLE
"no simulation" mode allows user to start the simulation

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto#64]
After loading NeuroML C.elegans pvdr Neuron (no simulation) user can click "Start" button. Doing so, increases CPU usage, even if nothing is going on on the screen. Pausing decreases CPU usage.

Originally filed by @msasinski 

Transferred here from the main OpenWorm board in [this issue](https://github.com/openworm/OpenWorm/issues/190)

**Comment by tarelli** [comment]
Obsolete
